DROP TABLE IF EXISTS City;
CREATE TABLE City (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `numbeo_id` INTEGER DEFAULT 0,
    `name` TEXT NOT NULL, 
    `region` TEXT NOT NULL, 
    `country` TEXT NOT NULL DEFAULT 'US'
);

INSERT INTO City (`name`, `region`) VALUES("Aberdeen", "SD");
INSERT INTO City (`name`, `region`) VALUES("Aberdeen", "WA");
INSERT INTO City (`name`, `region`) VALUES("Abilene", "TX");
INSERT INTO City (`name`, `region`) VALUES("Abingdon", "MD");
INSERT INTO City (`name`, `region`) VALUES("Acton", "MA");
INSERT INTO City (`name`, `region`) VALUES("Acworth", "GA");
INSERT INTO City (`name`, `region`) VALUES("Ada", "OK");
INSERT INTO City (`name`, `region`) VALUES("Addison IL", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Adelanto", "CA");
INSERT INTO City (`name`, `region`) VALUES("Adrian", "MI");
INSERT INTO City (`name`, `region`) VALUES("Agoura Hills", "CA");
INSERT INTO City (`name`, `region`) VALUES("Aiken", "SC");
INSERT INTO City (`name`, `region`) VALUES("Airway Heights", "WA");
INSERT INTO City (`name`, `region`) VALUES("Akron", "OH");
INSERT INTO City (`name`, `region`) VALUES("Alameda", "CA");
INSERT INTO City (`name`, `region`) VALUES("Alamogordo", "NM");
INSERT INTO City (`name`, `region`) VALUES("Alamosa", "CO");
INSERT INTO City (`name`, `region`) VALUES("Albany", "GA");
INSERT INTO City (`name`, `region`) VALUES("Albany", "NY");
INSERT INTO City (`name`, `region`) VALUES("Albany", "OR");
INSERT INTO City (`name`, `region`) VALUES("Albert Lea", "MN");
INSERT INTO City (`name`, `region`) VALUES("Albrightsville", "PA");
INSERT INTO City (`name`, `region`) VALUES("Albuquerque", "NM");
INSERT INTO City (`name`, `region`) VALUES("Alexandria", "LA");
INSERT INTO City (`name`, `region`) VALUES("Alexandria", "MN");
INSERT INTO City (`name`, `region`) VALUES("Alexandria", "VA");
INSERT INTO City (`name`, `region`) VALUES("Alhambra", "CA");
INSERT INTO City (`name`, `region`) VALUES("Aliso Viejo", "CA");
INSERT INTO City (`name`, `region`) VALUES("Allegan", "MI");
INSERT INTO City (`name`, `region`) VALUES("Allen", "TX");
INSERT INTO City (`name`, `region`) VALUES("Allentown", "PA");
INSERT INTO City (`name`, `region`) VALUES("Alpena", "MI");
INSERT INTO City (`name`, `region`) VALUES("Alpha", "IL");
INSERT INTO City (`name`, `region`) VALUES("Alpharetta", "GA");
INSERT INTO City (`name`, `region`) VALUES("Alpine", "TX");
INSERT INTO City (`name`, `region`) VALUES("Alton", "IL");
INSERT INTO City (`name`, `region`) VALUES("Altoona", "PA");
INSERT INTO City (`name`, `region`) VALUES("Alvin", "TX");
INSERT INTO City (`name`, `region`) VALUES("Amarillo", "TX");
INSERT INTO City (`name`, `region`) VALUES("Ames", "IA");
INSERT INTO City (`name`, `region`) VALUES("Amherst", "MA");
INSERT INTO City (`name`, `region`) VALUES("Amityville", "NY");
INSERT INTO City (`name`, `region`) VALUES("Anaheim", "CA");
INSERT INTO City (`name`, `region`) VALUES("Anchorage", "AK");
INSERT INTO City (`name`, `region`) VALUES("Anderson", "CA");
INSERT INTO City (`name`, `region`) VALUES("Anderson", "IN");
INSERT INTO City (`name`, `region`) VALUES("Anderson", "SC");
INSERT INTO City (`name`, `region`) VALUES("Andover", "MA");
INSERT INTO City (`name`, `region`) VALUES("Andover", "MN");
INSERT INTO City (`name`, `region`) VALUES("Angleton", "TX");
INSERT INTO City (`name`, `region`) VALUES("Angola", "IN");
INSERT INTO City (`name`, `region`) VALUES("Ankeny", "IA");
INSERT INTO City (`name`, `region`) VALUES("Ann Arbor", "MI");
INSERT INTO City (`name`, `region`) VALUES("Anna", "Texas");
INSERT INTO City (`name`, `region`) VALUES("Annapolis", "MD");
INSERT INTO City (`name`, `region`) VALUES("Antioch", "CA");
INSERT INTO City (`name`, `region`) VALUES("Apopka", "FL");
INSERT INTO City (`name`, `region`) VALUES("Apple Valley", "CA");
INSERT INTO City (`name`, `region`) VALUES("Apple Valley", "MN");
INSERT INTO City (`name`, `region`) VALUES("Appleton", "WI");
INSERT INTO City (`name`, `region`) VALUES("Archbold", "OH");
INSERT INTO City (`name`, `region`) VALUES("Arlington Heights", "IL");
INSERT INTO City (`name`, `region`) VALUES("Arlington", "KY");
INSERT INTO City (`name`, `region`) VALUES("Arlington", "TX");
INSERT INTO City (`name`, `region`) VALUES("Arlington", "VA");
INSERT INTO City (`name`, `region`) VALUES("Arlington", "WA");
INSERT INTO City (`name`, `region`) VALUES("Arroyo Grande", "CA");
INSERT INTO City (`name`, `region`) VALUES("Artesia", "NM");
INSERT INTO City (`name`, `region`) VALUES("Ashburn", "VA");
INSERT INTO City (`name`, `region`) VALUES("Asheville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Ashland", "MA");
INSERT INTO City (`name`, `region`) VALUES("Ashland", "OH");
INSERT INTO City (`name`, `region`) VALUES("Ashland", "WI");
INSERT INTO City (`name`, `region`) VALUES("Aspen", "CO");
INSERT INTO City (`name`, `region`) VALUES("Astoria", "NY");
INSERT INTO City (`name`, `region`) VALUES("Astoria", "OR");
INSERT INTO City (`name`, `region`) VALUES("Atascadero", "CA");
INSERT INTO City (`name`, `region`) VALUES("Athens", "GA");
INSERT INTO City (`name`, `region`) VALUES("Athens", "OH");
INSERT INTO City (`name`, `region`) VALUES("Athens", "TN");
INSERT INTO City (`name`, `region`) VALUES("Atlanta", "GA");
INSERT INTO City (`name`, `region`) VALUES("Atlantic City", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Attleboro", "MA");
INSERT INTO City (`name`, `region`) VALUES("Auburn", "AL");
INSERT INTO City (`name`, `region`) VALUES("Auburn", "WA");
INSERT INTO City (`name`, `region`) VALUES("Auburndale", "FL");
INSERT INTO City (`name`, `region`) VALUES("Augusta", "GA");
INSERT INTO City (`name`, `region`) VALUES("Augusta", "ME");
INSERT INTO City (`name`, `region`) VALUES("Aurora", "CO");
INSERT INTO City (`name`, `region`) VALUES("Aurora", "IL");
INSERT INTO City (`name`, `region`) VALUES("Austin", "MN");
INSERT INTO City (`name`, `region`) VALUES("Austin", "TX");
INSERT INTO City (`name`, `region`) VALUES("Avon", "CO");
INSERT INTO City (`name`, `region`) VALUES("Avon", "IN");
INSERT INTO City (`name`, `region`) VALUES("Avondale", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Bainbridge Island", "WA");
INSERT INTO City (`name`, `region`) VALUES("Baker City", "OR");
INSERT INTO City (`name`, `region`) VALUES("Bakersfield", "CA");
INSERT INTO City (`name`, `region`) VALUES("Baltimore", "MD");
INSERT INTO City (`name`, `region`) VALUES("Bangor", "ME");
INSERT INTO City (`name`, `region`) VALUES("Bar Harbor", "ME");
INSERT INTO City (`name`, `region`) VALUES("Baraboo", "WI");
INSERT INTO City (`name`, `region`) VALUES("Barnegat", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Barnstable", "MA");
INSERT INTO City (`name`, `region`) VALUES("Barrington", "IL");
INSERT INTO City (`name`, `region`) VALUES("Basking Ridge", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Batavia", "IL");
INSERT INTO City (`name`, `region`) VALUES("Baton Rouge", "LA");
INSERT INTO City (`name`, `region`) VALUES("Battle Creek", "MI");
INSERT INTO City (`name`, `region`) VALUES("Bay Minette", "AL");
INSERT INTO City (`name`, `region`) VALUES("Bayonne", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Baytown", "TX");
INSERT INTO City (`name`, `region`) VALUES("Baywood-Los Osos", "CA");
INSERT INTO City (`name`, `region`) VALUES("Beach Haven", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Beaufort", "SC");
INSERT INTO City (`name`, `region`) VALUES("Beaumont", "TX");
INSERT INTO City (`name`, `region`) VALUES("Beaver Dam", "WI");
INSERT INTO City (`name`, `region`) VALUES("Beaverton", "OR");
INSERT INTO City (`name`, `region`) VALUES("Beckley", "WV");
INSERT INTO City (`name`, `region`) VALUES("Bedford", "MA");
INSERT INTO City (`name`, `region`) VALUES("Bedminster Township", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Belleville", "IL");
INSERT INTO City (`name`, `region`) VALUES("Bellevue", "NE");
INSERT INTO City (`name`, `region`) VALUES("Bellevue", "WA");
INSERT INTO City (`name`, `region`) VALUES("Bellingham", "WA");
INSERT INTO City (`name`, `region`) VALUES("Belmont", "CA");
INSERT INTO City (`name`, `region`) VALUES("Beloit", "WI");
INSERT INTO City (`name`, `region`) VALUES("Bemidji", "MN");
INSERT INTO City (`name`, `region`) VALUES("Bend", "OR");
INSERT INTO City (`name`, `region`) VALUES("Bentonville", "AR");
INSERT INTO City (`name`, `region`) VALUES("Bergen County", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Berkeley Heights", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Berkeley", "CA");
INSERT INTO City (`name`, `region`) VALUES("Berwyn", "IL");
INSERT INTO City (`name`, `region`) VALUES("Bethel", "AK");
INSERT INTO City (`name`, `region`) VALUES("Bethesda", "MD");
INSERT INTO City (`name`, `region`) VALUES("Bethlehem", "PA");
INSERT INTO City (`name`, `region`) VALUES("Beverly Hills", "CA");
INSERT INTO City (`name`, `region`) VALUES("Beverly Hills", "FL");
INSERT INTO City (`name`, `region`) VALUES("Big Rapids", "MI");
INSERT INTO City (`name`, `region`) VALUES("Billings", "MT");
INSERT INTO City (`name`, `region`) VALUES("Biloxi", "MS");
INSERT INTO City (`name`, `region`) VALUES("Binghamton", "NY");
INSERT INTO City (`name`, `region`) VALUES("Birch Run", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Birmingham", "AL");
INSERT INTO City (`name`, `region`) VALUES("Bishop", "CA");
INSERT INTO City (`name`, `region`) VALUES("Bismarck", "ND");
INSERT INTO City (`name`, `region`) VALUES("Blacksburg", "VA");
INSERT INTO City (`name`, `region`) VALUES("Blaine", "WA");
INSERT INTO City (`name`, `region`) VALUES("Bloomfield Hills", "MI");
INSERT INTO City (`name`, `region`) VALUES("Bloomfield", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Bloomington", "IL");
INSERT INTO City (`name`, `region`) VALUES("Bloomington", "IN");
INSERT INTO City (`name`, `region`) VALUES("Bluefield", "WV");
INSERT INTO City (`name`, `region`) VALUES("Boca Raton", "FL");
INSERT INTO City (`name`, `region`) VALUES("Boise", "ID");
INSERT INTO City (`name`, `region`) VALUES("Bolingbrook", "IL");
INSERT INTO City (`name`, `region`) VALUES("Bonney Lake", "WA");
INSERT INTO City (`name`, `region`) VALUES("Boone", "NC");
INSERT INTO City (`name`, `region`) VALUES("Boston", "MA");
INSERT INTO City (`name`, `region`) VALUES("Bothell", "WA");
INSERT INTO City (`name`, `region`) VALUES("Boulder", "CO");
INSERT INTO City (`name`, `region`) VALUES("Bourbonnais", "IL");
INSERT INTO City (`name`, `region`) VALUES("Bourne", "MA");
INSERT INTO City (`name`, `region`) VALUES("Bowie", "MD");
INSERT INTO City (`name`, `region`) VALUES("Bowling Green", "KY");
INSERT INTO City (`name`, `region`) VALUES("Bowling Green", "OH");
INSERT INTO City (`name`, `region`) VALUES("Boynton Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Bozeman", "MT");
INSERT INTO City (`name`, `region`) VALUES("Bradenton", "FL");
INSERT INTO City (`name`, `region`) VALUES("Bradford", "PA");
INSERT INTO City (`name`, `region`) VALUES("Bradley", "IL");
INSERT INTO City (`name`, `region`) VALUES("Brainerd", "MN");
INSERT INTO City (`name`, `region`) VALUES("Branson", "MO");
INSERT INTO City (`name`, `region`) VALUES("Brattleboro", "VT");
INSERT INTO City (`name`, `region`) VALUES("Brea", "CA");
INSERT INTO City (`name`, `region`) VALUES("Breckenridge", "CO");
INSERT INTO City (`name`, `region`) VALUES("Breckenridge,TX", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Bremerton", "WA");
INSERT INTO City (`name`, `region`) VALUES("Brentwood", "CA");
INSERT INTO City (`name`, `region`) VALUES("Brentwood", "TN");
INSERT INTO City (`name`, `region`) VALUES("Brevard", "NC");
INSERT INTO City (`name`, `region`) VALUES("Bridgeport", "CT");
INSERT INTO City (`name`, `region`) VALUES("Bridgewater", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Brier", "WA");
INSERT INTO City (`name`, `region`) VALUES("Brighton", "MI");
INSERT INTO City (`name`, `region`) VALUES("Bristol", "VA");
INSERT INTO City (`name`, `region`) VALUES("Brockton", "MA");
INSERT INTO City (`name`, `region`) VALUES("Bronx", "NY");
INSERT INTO City (`name`, `region`) VALUES("Brookhaven", "NY");
INSERT INTO City (`name`, `region`) VALUES("Brookings", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Brooklyn", "NY");
INSERT INTO City (`name`, `region`) VALUES("Brownsville", "TX");
INSERT INTO City (`name`, `region`) VALUES("Brunswick", "GA");
INSERT INTO City (`name`, `region`) VALUES("Brunswick", "ME");
INSERT INTO City (`name`, `region`) VALUES("Buckeye", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Buffalo Grove", "IL");
INSERT INTO City (`name`, `region`) VALUES("Buffalo", "NY");
INSERT INTO City (`name`, `region`) VALUES("Buford", "GA");
INSERT INTO City (`name`, `region`) VALUES("Bullhead City", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Bulverde", "TX");
INSERT INTO City (`name`, `region`) VALUES("Burbank", "CA");
INSERT INTO City (`name`, `region`) VALUES("Burlington", "IA");
INSERT INTO City (`name`, `region`) VALUES("Burlington", "MA");
INSERT INTO City (`name`, `region`) VALUES("Burlington", "VT");
INSERT INTO City (`name`, `region`) VALUES("Burnsville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Butte", "MT");
INSERT INTO City (`name`, `region`) VALUES("Cabot", "AR");
INSERT INTO City (`name`, `region`) VALUES("Cadillac", "MI");
INSERT INTO City (`name`, `region`) VALUES("California", "MD");
INSERT INTO City (`name`, `region`) VALUES("Camarillo", "CA");
INSERT INTO City (`name`, `region`) VALUES("Cambridge", "MA");
INSERT INTO City (`name`, `region`) VALUES("Cambridge", "OH");
INSERT INTO City (`name`, `region`) VALUES("Camden", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Canoga Park", "CA");
INSERT INTO City (`name`, `region`) VALUES("Canon City", "CO");
INSERT INTO City (`name`, `region`) VALUES("Canton", "OH");
INSERT INTO City (`name`, `region`) VALUES("Cape Canaveral", "FL");
INSERT INTO City (`name`, `region`) VALUES("Cape Carteret", "NC");
INSERT INTO City (`name`, `region`) VALUES("Cape Charles", "VA");
INSERT INTO City (`name`, `region`) VALUES("Cape Coral", "FL");
INSERT INTO City (`name`, `region`) VALUES("Cape Girardeau", "MO");
INSERT INTO City (`name`, `region`) VALUES("Cape May Court House", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Carbondale", "IL");
INSERT INTO City (`name`, `region`) VALUES("Carlsbad", "CA");
INSERT INTO City (`name`, `region`) VALUES("Carlsbad", "NM");
INSERT INTO City (`name`, `region`) VALUES("Carmel", "IN");
INSERT INTO City (`name`, `region`) VALUES("Carson City", "NV");
INSERT INTO City (`name`, `region`) VALUES("Carson", "CA");
INSERT INTO City (`name`, `region`) VALUES("Cartersville", "GA");
INSERT INTO City (`name`, `region`) VALUES("Cary", "NC");
INSERT INTO City (`name`, `region`) VALUES("Casper", "WY");
INSERT INTO City (`name`, `region`) VALUES("Castle Rock", "CO");
INSERT INTO City (`name`, `region`) VALUES("Castro Valley", "CA");
INSERT INTO City (`name`, `region`) VALUES("Catonsville", "MD");
INSERT INTO City (`name`, `region`) VALUES("Cave City", "KY");
INSERT INTO City (`name`, `region`) VALUES("Cave Creek", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Cedar City", "UT");
INSERT INTO City (`name`, `region`) VALUES("Cedar Rapids", "IA");
INSERT INTO City (`name`, `region`) VALUES("Cedartown", "GA");
INSERT INTO City (`name`, `region`) VALUES("Central Valley", "NY");
INSERT INTO City (`name`, `region`) VALUES("Centreville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Cerritos", "CA");
INSERT INTO City (`name`, `region`) VALUES("Champaign", "IL");
INSERT INTO City (`name`, `region`) VALUES("Chandler", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Chantilly", "VA");
INSERT INTO City (`name`, `region`) VALUES("Chapel Hill", "NC");
INSERT INTO City (`name`, `region`) VALUES("Charles Town", "WV");
INSERT INTO City (`name`, `region`) VALUES("Charleston", "SC");
INSERT INTO City (`name`, `region`) VALUES("Charleston", "WV");
INSERT INTO City (`name`, `region`) VALUES("Charlotte", "NC");
INSERT INTO City (`name`, `region`) VALUES("Charlottesville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Chattanooga", "TN");
INSERT INTO City (`name`, `region`) VALUES("Chelan", "WA");
INSERT INTO City (`name`, `region`) VALUES("Cherry Hill", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Chesapeake", "VA");
INSERT INTO City (`name`, `region`) VALUES("Chesterfield", "MI");
INSERT INTO City (`name`, `region`) VALUES("Chesterfield", "MO");
INSERT INTO City (`name`, `region`) VALUES("Chevy Chase", "MD");
INSERT INTO City (`name`, `region`) VALUES("Cheyenne", "WY");
INSERT INTO City (`name`, `region`) VALUES("Chicago", "IL");
INSERT INTO City (`name`, `region`) VALUES("Chico", "CA");
INSERT INTO City (`name`, `region`) VALUES("Christiansburg", "VA");
INSERT INTO City (`name`, `region`) VALUES("Chula Vista", "CA");
INSERT INTO City (`name`, `region`) VALUES("Cincinnati", "OH");
INSERT INTO City (`name`, `region`) VALUES("Citrus Heights", "CA");
INSERT INTO City (`name`, `region`) VALUES("Clarion", "PA");
INSERT INTO City (`name`, `region`) VALUES("Clarkston", "GA");
INSERT INTO City (`name`, `region`) VALUES("Clarkston", "WA");
INSERT INTO City (`name`, `region`) VALUES("Clarksville", "TN");
INSERT INTO City (`name`, `region`) VALUES("Clayton", "NC");
INSERT INTO City (`name`, `region`) VALUES("Clear Lake", "IA");
INSERT INTO City (`name`, `region`) VALUES("Clearfield", "PA");
INSERT INTO City (`name`, `region`) VALUES("Clearwater", "FL");
INSERT INTO City (`name`, `region`) VALUES("Clemson", "SC");
INSERT INTO City (`name`, `region`) VALUES("Cleveland", "MS");
INSERT INTO City (`name`, `region`) VALUES("Cleveland", "OH");
INSERT INTO City (`name`, `region`) VALUES("Cleveland", "TN");
INSERT INTO City (`name`, `region`) VALUES("Clewiston", "FL");
INSERT INTO City (`name`, `region`) VALUES("Clifton Park", "NY");
INSERT INTO City (`name`, `region`) VALUES("Clifton", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Clifton", "TN");
INSERT INTO City (`name`, `region`) VALUES("Clinton Township", "MI");
INSERT INTO City (`name`, `region`) VALUES("Clinton", "IA");
INSERT INTO City (`name`, `region`) VALUES("Clinton", "MO");
INSERT INTO City (`name`, `region`) VALUES("Clovis", " NM");
INSERT INTO City (`name`, `region`) VALUES("Cody", "WY");
INSERT INTO City (`name`, `region`) VALUES("Coeur d'Alene", "ID");
INSERT INTO City (`name`, `region`) VALUES("College Park", "MD");
INSERT INTO City (`name`, `region`) VALUES("College Station", "TX");
INSERT INTO City (`name`, `region`) VALUES("Collins", "MS");
INSERT INTO City (`name`, `region`) VALUES("Colorado Springs", "CO");
INSERT INTO City (`name`, `region`) VALUES("Columbia", "MD");
INSERT INTO City (`name`, `region`) VALUES("Columbia", "MO");
INSERT INTO City (`name`, `region`) VALUES("Columbia", "SC");
INSERT INTO City (`name`, `region`) VALUES("Columbia", "TN");
INSERT INTO City (`name`, `region`) VALUES("Columbus", "GA");
INSERT INTO City (`name`, `region`) VALUES("Columbus", "IN");
INSERT INTO City (`name`, `region`) VALUES("Columbus", "OH");
INSERT INTO City (`name`, `region`) VALUES("Commack", "NY");
INSERT INTO City (`name`, `region`) VALUES("Commerce", "MI");
INSERT INTO City (`name`, `region`) VALUES("Concord", "CA");
INSERT INTO City (`name`, `region`) VALUES("Concord", "NC");
INSERT INTO City (`name`, `region`) VALUES("Concord", "NH");
INSERT INTO City (`name`, `region`) VALUES("Congers", "NY");
INSERT INTO City (`name`, `region`) VALUES("Conroe", "TX");
INSERT INTO City (`name`, `region`) VALUES("Conway", "AR");
INSERT INTO City (`name`, `region`) VALUES("Conway", "SC");
INSERT INTO City (`name`, `region`) VALUES("Cookeville", "TN");
INSERT INTO City (`name`, `region`) VALUES("Coon Rapids", "MN");
INSERT INTO City (`name`, `region`) VALUES("Coos Bay", "OR");
INSERT INTO City (`name`, `region`) VALUES("Coppell", "TX");
INSERT INTO City (`name`, `region`) VALUES("Copperopolis", "CA");
INSERT INTO City (`name`, `region`) VALUES("Coral Springs", "FL");
INSERT INTO City (`name`, `region`) VALUES("Corning", "NY");
INSERT INTO City (`name`, `region`) VALUES("Corona", "CA");
INSERT INTO City (`name`, `region`) VALUES("Corpus Christi", "TX");
INSERT INTO City (`name`, `region`) VALUES("Corvallis", "OR");
INSERT INTO City (`name`, `region`) VALUES("Costa Mesa", "CA");
INSERT INTO City (`name`, `region`) VALUES("Cottonwood", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Covington", "LA");
INSERT INTO City (`name`, `region`) VALUES("Cranberry Township", "PA");
INSERT INTO City (`name`, `region`) VALUES("Cranford", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Crawfordsville", "IN");
INSERT INTO City (`name`, `region`) VALUES("Crestview", "FL");
INSERT INTO City (`name`, `region`) VALUES("Crown Point", "IN");
INSERT INTO City (`name`, `region`) VALUES("Crystal Lake", "IL");
INSERT INTO City (`name`, `region`) VALUES("Cumberland", "MD");
INSERT INTO City (`name`, `region`) VALUES("Cumberland", "RI");
INSERT INTO City (`name`, `region`) VALUES("Cumming", "GA");
INSERT INTO City (`name`, `region`) VALUES("Cupertino", "CA");
INSERT INTO City (`name`, `region`) VALUES("Cut Bank", "MT");
INSERT INTO City (`name`, `region`) VALUES("Cutler Bay", "FL");
INSERT INTO City (`name`, `region`) VALUES("Dallas", "TX");
INSERT INTO City (`name`, `region`) VALUES("Dalton", "GA");
INSERT INTO City (`name`, `region`) VALUES("Danbury", "CT");
INSERT INTO City (`name`, `region`) VALUES("Danville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Danville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Davenport", "IA");
INSERT INTO City (`name`, `region`) VALUES("Davis", "CA");
INSERT INTO City (`name`, `region`) VALUES("Dayton", "OH");
INSERT INTO City (`name`, `region`) VALUES("Daytona Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("DeLand", "FL");
INSERT INTO City (`name`, `region`) VALUES("Decatur", "AL");
INSERT INTO City (`name`, `region`) VALUES("Decatur", "IL");
INSERT INTO City (`name`, `region`) VALUES("Deerfield Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Defuniak Springs", "FL");
INSERT INTO City (`name`, `region`) VALUES("Del Rio", "TX");
INSERT INTO City (`name`, `region`) VALUES("Delaware", "OH");
INSERT INTO City (`name`, `region`) VALUES("Delray Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Deltona", "FL");
INSERT INTO City (`name`, `region`) VALUES("Denton", "TX");
INSERT INTO City (`name`, `region`) VALUES("Denver", "CO");
INSERT INTO City (`name`, `region`) VALUES("Derry", "NH");
INSERT INTO City (`name`, `region`) VALUES("Des Moines", "IA");
INSERT INTO City (`name`, `region`) VALUES("Des Plaines", "IL");
INSERT INTO City (`name`, `region`) VALUES("Desert Hot Springs", "CA");
INSERT INTO City (`name`, `region`) VALUES("Detroit", "MI");
INSERT INTO City (`name`, `region`) VALUES("Dickinson", "ND");
INSERT INTO City (`name`, `region`) VALUES("Dillingham", "AK");
INSERT INTO City (`name`, `region`) VALUES("Dixon", "IL");
INSERT INTO City (`name`, `region`) VALUES("Dodge City", "KS");
INSERT INTO City (`name`, `region`) VALUES("Dothan", "AL");
INSERT INTO City (`name`, `region`) VALUES("Douglas", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Dover", "DE");
INSERT INTO City (`name`, `region`) VALUES("Dover", "NH");
INSERT INTO City (`name`, `region`) VALUES("Downey", "CA");
INSERT INTO City (`name`, `region`) VALUES("Downingtown", "PA");
INSERT INTO City (`name`, `region`) VALUES("Doylestown", "PA");
INSERT INTO City (`name`, `region`) VALUES("Dublin", "OH");
INSERT INTO City (`name`, `region`) VALUES("Dubuque", "IA");
INSERT INTO City (`name`, `region`) VALUES("Duluth", "GA");
INSERT INTO City (`name`, `region`) VALUES("Duluth", "MN");
INSERT INTO City (`name`, `region`) VALUES("Duncan", "OK");
INSERT INTO City (`name`, `region`) VALUES("Durango", "CO");
INSERT INTO City (`name`, `region`) VALUES("Durant", "OK");
INSERT INTO City (`name`, `region`) VALUES("Durham", "NC");
INSERT INTO City (`name`, `region`) VALUES("Eagan", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Eagle River", "AK");
INSERT INTO City (`name`, `region`) VALUES("East Chicago", "IN");
INSERT INTO City (`name`, `region`) VALUES("East Hampton", "NY");
INSERT INTO City (`name`, `region`) VALUES("East Lansing", "MI");
INSERT INTO City (`name`, `region`) VALUES("East Northport", "NY");
INSERT INTO City (`name`, `region`) VALUES("East Orange", "NJ");
INSERT INTO City (`name`, `region`) VALUES("East Providence", "RI");
INSERT INTO City (`name`, `region`) VALUES("East Rutherford", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Easton", "MD");
INSERT INTO City (`name`, `region`) VALUES("Eastpointe", "MI");
INSERT INTO City (`name`, `region`) VALUES("Eau Claire", "WI");
INSERT INTO City (`name`, `region`) VALUES("Eden Prairie", "MN");
INSERT INTO City (`name`, `region`) VALUES("Edgewood", "KY");
INSERT INTO City (`name`, `region`) VALUES("Edison", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Edmond", "OK");
INSERT INTO City (`name`, `region`) VALUES("Edwardsville", "IL");
INSERT INTO City (`name`, `region`) VALUES("Effingham", "IL");
INSERT INTO City (`name`, `region`) VALUES("El Cajon", "CA");
INSERT INTO City (`name`, `region`) VALUES("El Centro", "CA");
INSERT INTO City (`name`, `region`) VALUES("El Cerrito", "CA");
INSERT INTO City (`name`, `region`) VALUES("El Dorado", "AR");
INSERT INTO City (`name`, `region`) VALUES("El Paso", "TX");
INSERT INTO City (`name`, `region`) VALUES("Eldersburg", "MD");
INSERT INTO City (`name`, `region`) VALUES("Eldon", "MO");
INSERT INTO City (`name`, `region`) VALUES("Elizabeth", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Elizabethton", "TN");
INSERT INTO City (`name`, `region`) VALUES("Elizabethtown", "KY");
INSERT INTO City (`name`, `region`) VALUES("Elkhart", "IN");
INSERT INTO City (`name`, `region`) VALUES("Elkhorn", "WI");
INSERT INTO City (`name`, `region`) VALUES("Elko", "NV");
INSERT INTO City (`name`, `region`) VALUES("Elkton", "MD");
INSERT INTO City (`name`, `region`) VALUES("Ellensburg", "WA");
INSERT INTO City (`name`, `region`) VALUES("Ellsworth", "ME");
INSERT INTO City (`name`, `region`) VALUES("Elmira", "NY");
INSERT INTO City (`name`, `region`) VALUES("Emporia", "KS");
INSERT INTO City (`name`, `region`) VALUES("Encinitas", "CA");
INSERT INTO City (`name`, `region`) VALUES("Enterprise", "Al");
INSERT INTO City (`name`, `region`) VALUES("Erie", "PA");
INSERT INTO City (`name`, `region`) VALUES("Erlanger", "KY");
INSERT INTO City (`name`, `region`) VALUES("Escondido", "CA");
INSERT INTO City (`name`, `region`) VALUES("Eugene", "OR");
INSERT INTO City (`name`, `region`) VALUES("Eureka", "CA");
INSERT INTO City (`name`, `region`) VALUES("Evans", "GA");
INSERT INTO City (`name`, `region`) VALUES("Evanston", "IL");
INSERT INTO City (`name`, `region`) VALUES("Evanston", "WY");
INSERT INTO City (`name`, `region`) VALUES("Evansville", "IN");
INSERT INTO City (`name`, `region`) VALUES("Everett", "MA");
INSERT INTO City (`name`, `region`) VALUES("Everett", "WA");
INSERT INTO City (`name`, `region`) VALUES("Fairbanks", "AK");
INSERT INTO City (`name`, `region`) VALUES("Fairborn", "OH");
INSERT INTO City (`name`, `region`) VALUES("Fairfax", "VA");
INSERT INTO City (`name`, `region`) VALUES("Fairfield", "CA");
INSERT INTO City (`name`, `region`) VALUES("Fairfield", "CT");
INSERT INTO City (`name`, `region`) VALUES("Fairmont", "WV");
INSERT INTO City (`name`, `region`) VALUES("Fall River", "MA");
INSERT INTO City (`name`, `region`) VALUES("Fallbrook", "CA");
INSERT INTO City (`name`, `region`) VALUES("Fargo", "ND");
INSERT INTO City (`name`, `region`) VALUES("Farmington Hills", "MI");
INSERT INTO City (`name`, `region`) VALUES("Farmington", "CT");
INSERT INTO City (`name`, `region`) VALUES("Farmington", "MO");
INSERT INTO City (`name`, `region`) VALUES("Farmington", "NM");
INSERT INTO City (`name`, `region`) VALUES("Fayettevill", "GA");
INSERT INTO City (`name`, `region`) VALUES("Fayetteville", "AR");
INSERT INTO City (`name`, `region`) VALUES("Fayetteville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Fennimore", "WI");
INSERT INTO City (`name`, `region`) VALUES("Fishkill", "NY");
INSERT INTO City (`name`, `region`) VALUES("Flagstaff", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Flanders", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Flemington", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Flint", "MI");
INSERT INTO City (`name`, `region`) VALUES("Florence", "AL");
INSERT INTO City (`name`, `region`) VALUES("Florence", "KY");
INSERT INTO City (`name`, `region`) VALUES("Florence", "SC");
INSERT INTO City (`name`, `region`) VALUES("Fond du Lac", "WI");
INSERT INTO City (`name`, `region`) VALUES("Fontana", "CA");
INSERT INTO City (`name`, `region`) VALUES("Forsyth", "GA");
INSERT INTO City (`name`, `region`) VALUES("Forsyth", "MT");
INSERT INTO City (`name`, `region`) VALUES("Fort Collins", "CO");
INSERT INTO City (`name`, `region`) VALUES("Fort Dodge", "IA");
INSERT INTO City (`name`, `region`) VALUES("Fort Lauderdale", "FL");
INSERT INTO City (`name`, `region`) VALUES("Fort Lee", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Fort Myers", "FL");
INSERT INTO City (`name`, `region`) VALUES("Fort Pierce", "FL");
INSERT INTO City (`name`, `region`) VALUES("Fort Scott", "KS");
INSERT INTO City (`name`, `region`) VALUES("Fort Smith", "AR");
INSERT INTO City (`name`, `region`) VALUES("Fort Walton Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Fort Wayne", "IN");
INSERT INTO City (`name`, `region`) VALUES("Fort Worth", "TX");
INSERT INTO City (`name`, `region`) VALUES("Fortuna", "CA");
INSERT INTO City (`name`, `region`) VALUES("Foster City", "CA");
INSERT INTO City (`name`, `region`) VALUES("Fowlerville", "MI");
INSERT INTO City (`name`, `region`) VALUES("Fox River Grove", "IL");
INSERT INTO City (`name`, `region`) VALUES("Framingham", "MA");
INSERT INTO City (`name`, `region`) VALUES("Frankfort", "KY");
INSERT INTO City (`name`, `region`) VALUES("Franklin", "NC");
INSERT INTO City (`name`, `region`) VALUES("Franklin", "TN");
INSERT INTO City (`name`, `region`) VALUES("Frederick", "MD");
INSERT INTO City (`name`, `region`) VALUES("Fredericksburg", "TX");
INSERT INTO City (`name`, `region`) VALUES("Fredericksburg", "VA");
INSERT INTO City (`name`, `region`) VALUES("Fremont", "CA");
INSERT INTO City (`name`, `region`) VALUES("Fresno", "CA");
INSERT INTO City (`name`, `region`) VALUES("Frisco", "TX");
INSERT INTO City (`name`, `region`) VALUES("Frogtown", "MS");
INSERT INTO City (`name`, `region`) VALUES("Fullerton", "CA");
INSERT INTO City (`name`, `region`) VALUES("Fulshear", "TX");
INSERT INTO City (`name`, `region`) VALUES("Fuquay-Varina", "NC");
INSERT INTO City (`name`, `region`) VALUES("Gadsden", "AL");
INSERT INTO City (`name`, `region`) VALUES("Gainesville", "FL");
INSERT INTO City (`name`, `region`) VALUES("Gainesville", "GA");
INSERT INTO City (`name`, `region`) VALUES("Gainesville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Gaithersburg", "MD");
INSERT INTO City (`name`, `region`) VALUES("Galesburg", "IL");
INSERT INTO City (`name`, `region`) VALUES("Gallup", "NM");
INSERT INTO City (`name`, `region`) VALUES("Galveston", "TX");
INSERT INTO City (`name`, `region`) VALUES("Garberville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Garden City", "NY");
INSERT INTO City (`name`, `region`) VALUES("Garden Grove", "CA");
INSERT INTO City (`name`, `region`) VALUES("Garland", "TX");
INSERT INTO City (`name`, `region`) VALUES("Gary", "IN");
INSERT INTO City (`name`, `region`) VALUES("Gastonia", "NC");
INSERT INTO City (`name`, `region`) VALUES("Gaylord", "MI");
INSERT INTO City (`name`, `region`) VALUES("Geneva", "IL");
INSERT INTO City (`name`, `region`) VALUES("Georgetown", "KY");
INSERT INTO City (`name`, `region`) VALUES("Gering", "NE");
INSERT INTO City (`name`, `region`) VALUES("Germantown", "MD");
INSERT INTO City (`name`, `region`) VALUES("Germantown", "TN");
INSERT INTO City (`name`, `region`) VALUES("Gig Harbor", "WA");
INSERT INTO City (`name`, `region`) VALUES("Gilbert", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Gillette", "WY");
INSERT INTO City (`name`, `region`) VALUES("Gilroy", "CA");
INSERT INTO City (`name`, `region`) VALUES("Glasgow", "KY");
INSERT INTO City (`name`, `region`) VALUES("Glendale Heights", "IL");
INSERT INTO City (`name`, `region`) VALUES("Glendale", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Glendale", "CA");
INSERT INTO City (`name`, `region`) VALUES("Glendora", "CA");
INSERT INTO City (`name`, `region`) VALUES("Gloucester", "MA");
INSERT INTO City (`name`, `region`) VALUES("Goldsboro", "NC");
INSERT INTO City (`name`, `region`) VALUES("Gonzales", "LA");
INSERT INTO City (`name`, `region`) VALUES("Goose Creek", "SC");
INSERT INTO City (`name`, `region`) VALUES("Granbury", "TX");
INSERT INTO City (`name`, `region`) VALUES("Grand Forks", "ND");
INSERT INTO City (`name`, `region`) VALUES("Grand Island", "NE");
INSERT INTO City (`name`, `region`) VALUES("Grand Junction", "CO");
INSERT INTO City (`name`, `region`) VALUES("Grand Rapids", "MI");
INSERT INTO City (`name`, `region`) VALUES("Grants Pass", "OR");
INSERT INTO City (`name`, `region`) VALUES("Grapevine", "TX");
INSERT INTO City (`name`, `region`) VALUES("Grass Valley", "CA");
INSERT INTO City (`name`, `region`) VALUES("Great Bend", "KS");
INSERT INTO City (`name`, `region`) VALUES("Great Falls", "MT");
INSERT INTO City (`name`, `region`) VALUES("Greeley", "CO");
INSERT INTO City (`name`, `region`) VALUES("Green Bay", "WI");
INSERT INTO City (`name`, `region`) VALUES("Green Valley", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Greene", "NY");
INSERT INTO City (`name`, `region`) VALUES("Greenfield", "IN");
INSERT INTO City (`name`, `region`) VALUES("Greenfield", "MA");
INSERT INTO City (`name`, `region`) VALUES("Greensboro", "NC");
INSERT INTO City (`name`, `region`) VALUES("Greensburg", "PA");
INSERT INTO City (`name`, `region`) VALUES("Greenville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Greenville", "PA");
INSERT INTO City (`name`, `region`) VALUES("Greenville", "SC");
INSERT INTO City (`name`, `region`) VALUES("Greenville", "TX");
INSERT INTO City (`name`, `region`) VALUES("Greenwich", "CT");
INSERT INTO City (`name`, `region`) VALUES("Greenwood", "IN");
INSERT INTO City (`name`, `region`) VALUES("Greenwood", "SC");
INSERT INTO City (`name`, `region`) VALUES("Gresham", "OR");
INSERT INTO City (`name`, `region`) VALUES("Grosse Pointe Woods", "MI");
INSERT INTO City (`name`, `region`) VALUES("Groton", "CT");
INSERT INTO City (`name`, `region`) VALUES("Grover Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Gulfport", "MS");
INSERT INTO City (`name`, `region`) VALUES("Guntersville", "AL");
INSERT INTO City (`name`, `region`) VALUES("Hackensack", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Hagerstown", "MD");
INSERT INTO City (`name`, `region`) VALUES("Hailey", "ID");
INSERT INTO City (`name`, `region`) VALUES("Haines", "AK");
INSERT INTO City (`name`, `region`) VALUES("Hamilton", "MT");
INSERT INTO City (`name`, `region`) VALUES("Hamilton", "OH");
INSERT INTO City (`name`, `region`) VALUES("Hammond", "LA");
INSERT INTO City (`name`, `region`) VALUES("Hampton", "VA");
INSERT INTO City (`name`, `region`) VALUES("Hanover", "NH");
INSERT INTO City (`name`, `region`) VALUES("Harlingen", "TX");
INSERT INTO City (`name`, `region`) VALUES("Harrington Park", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Harrisburg", "PA");
INSERT INTO City (`name`, `region`) VALUES("Harrison", "AR");
INSERT INTO City (`name`, `region`) VALUES("Harrisonburg va", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Hartford", "CT");
INSERT INTO City (`name`, `region`) VALUES("Hartsville", "SC");
INSERT INTO City (`name`, `region`) VALUES("Hattiesburg", "MS");
INSERT INTO City (`name`, `region`) VALUES("Havelock", "NC");
INSERT INTO City (`name`, `region`) VALUES("Hawthorne", "CA");
INSERT INTO City (`name`, `region`) VALUES("Hawthorne", "NV");
INSERT INTO City (`name`, `region`) VALUES("Hays", "KS");
INSERT INTO City (`name`, `region`) VALUES("Haysville", "KS");
INSERT INTO City (`name`, `region`) VALUES("Hayward", "CA");
INSERT INTO City (`name`, `region`) VALUES("Hazard", "KY");
INSERT INTO City (`name`, `region`) VALUES("Helena", "MT");
INSERT INTO City (`name`, `region`) VALUES("Hemet", "CA");
INSERT INTO City (`name`, `region`) VALUES("Hempstead", "NY");
INSERT INTO City (`name`, `region`) VALUES("Henderson", "NV");
INSERT INTO City (`name`, `region`) VALUES("Hermiston", "OR");
INSERT INTO City (`name`, `region`) VALUES("Hermosa Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Hernando", "FL");
INSERT INTO City (`name`, `region`) VALUES("Herndon", "VA");
INSERT INTO City (`name`, `region`) VALUES("Hialeah", "FL");
INSERT INTO City (`name`, `region`) VALUES("Hickory", "NC");
INSERT INTO City (`name`, `region`) VALUES("High Point", "NC");
INSERT INTO City (`name`, `region`) VALUES("Highland", "CA");
INSERT INTO City (`name`, `region`) VALUES("Highlands Ranch", "CO");
INSERT INTO City (`name`, `region`) VALUES("Hillsboro", "OR");
INSERT INTO City (`name`, `region`) VALUES("Hilo", "HI");
INSERT INTO City (`name`, `region`) VALUES("Hilton Head Island", "SC");
INSERT INTO City (`name`, `region`) VALUES("Hilton", "NY");
INSERT INTO City (`name`, `region`) VALUES("Hinesville", "GA");
INSERT INTO City (`name`, `region`) VALUES("Hobbs", "NM");
INSERT INTO City (`name`, `region`) VALUES("Hoboken", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Holland", "MI");
INSERT INTO City (`name`, `region`) VALUES("Hollywood", "FL");
INSERT INTO City (`name`, `region`) VALUES("Homestead", "FL");
INSERT INTO City (`name`, `region`) VALUES("Honolulu", "HI");
INSERT INTO City (`name`, `region`) VALUES("Hopkins", "MN");
INSERT INTO City (`name`, `region`) VALUES("Hot Springs", "AR");
INSERT INTO City (`name`, `region`) VALUES("Houghton", "MI");
INSERT INTO City (`name`, `region`) VALUES("Houston", "MO");
INSERT INTO City (`name`, `region`) VALUES("Houston", "TX");
INSERT INTO City (`name`, `region`) VALUES("Howard", "OH");
INSERT INTO City (`name`, `region`) VALUES("Hudson", "MA");
INSERT INTO City (`name`, `region`) VALUES("Huntington Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Huntington Park", "CA");
INSERT INTO City (`name`, `region`) VALUES("Huntington Woods", "MI");
INSERT INTO City (`name`, `region`) VALUES("Huntington", "WV");
INSERT INTO City (`name`, `region`) VALUES("Huntsville", "AL");
INSERT INTO City (`name`, `region`) VALUES("Huntsville", "TX");
INSERT INTO City (`name`, `region`) VALUES("Hutchinson", "KS");
INSERT INTO City (`name`, `region`) VALUES("Hyannis", "MA");
INSERT INTO City (`name`, `region`) VALUES("Hyattsville", "MD");
INSERT INTO City (`name`, `region`) VALUES("Idaho Falls", "ID");
INSERT INTO City (`name`, `region`) VALUES("Independence", "MO");
INSERT INTO City (`name`, `region`) VALUES("Indialantic", "FL");
INSERT INTO City (`name`, `region`) VALUES("Indianapolis", "IN");
INSERT INTO City (`name`, `region`) VALUES("Indio", "CA");
INSERT INTO City (`name`, `region`) VALUES("Iola", "KS");
INSERT INTO City (`name`, `region`) VALUES("Iowa City", "IA");
INSERT INTO City (`name`, `region`) VALUES("Ironton", "OH");
INSERT INTO City (`name`, `region`) VALUES("Ironwood", "MI");
INSERT INTO City (`name`, `region`) VALUES("Irvine", "CA");
INSERT INTO City (`name`, `region`) VALUES("Irving", "TX");
INSERT INTO City (`name`, `region`) VALUES("Isanti", "MN");
INSERT INTO City (`name`, `region`) VALUES("Islip", "NY");
INSERT INTO City (`name`, `region`) VALUES("Issaquah", "WA");
INSERT INTO City (`name`, `region`) VALUES("Ithaca", "NY");
INSERT INTO City (`name`, `region`) VALUES("Jacksboro", "TN");
INSERT INTO City (`name`, `region`) VALUES("Jackson", "MS");
INSERT INTO City (`name`, `region`) VALUES("Jackson", "TN");
INSERT INTO City (`name`, `region`) VALUES("Jackson", "WY");
INSERT INTO City (`name`, `region`) VALUES("Jacksonville", "FL");
INSERT INTO City (`name`, `region`) VALUES("Jacksonville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Jamestown", "NY");
INSERT INTO City (`name`, `region`) VALUES("Janesville", "WI");
INSERT INTO City (`name`, `region`) VALUES("Jefferson City", "MO");
INSERT INTO City (`name`, `region`) VALUES("Jeffersonville", "IN");
INSERT INTO City (`name`, `region`) VALUES("Jersey City", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Johnson City", "TN");
INSERT INTO City (`name`, `region`) VALUES("Johnstown", "PA");
INSERT INTO City (`name`, `region`) VALUES("Jonesboro", "AR");
INSERT INTO City (`name`, `region`) VALUES("Joplin", "MO");
INSERT INTO City (`name`, `region`) VALUES("Juneau", "AK");
INSERT INTO City (`name`, `region`) VALUES("Jupiter", "FL");
INSERT INTO City (`name`, `region`) VALUES("Kahului", "HI");
INSERT INTO City (`name`, `region`) VALUES("Kailua", "HI");
INSERT INTO City (`name`, `region`) VALUES("Kalamazoo", "MI");
INSERT INTO City (`name`, `region`) VALUES("Kalispell", "MT");
INSERT INTO City (`name`, `region`) VALUES("Kansas City", "KS");
INSERT INTO City (`name`, `region`) VALUES("Kansas City", "MO");
INSERT INTO City (`name`, `region`) VALUES("Katy", "TX");
INSERT INTO City (`name`, `region`) VALUES("Kearney", "NE");
INSERT INTO City (`name`, `region`) VALUES("Keene", "NH");
INSERT INTO City (`name`, `region`) VALUES("Keller", "TX");
INSERT INTO City (`name`, `region`) VALUES("Kennesaw", "GA");
INSERT INTO City (`name`, `region`) VALUES("Kennewick", "WA");
INSERT INTO City (`name`, `region`) VALUES("Kenosha", "WI");
INSERT INTO City (`name`, `region`) VALUES("Kent", "OH");
INSERT INTO City (`name`, `region`) VALUES("Kent", "WA");
INSERT INTO City (`name`, `region`) VALUES("Kernersville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Kerrville", "TX");
INSERT INTO City (`name`, `region`) VALUES("Ketchikan", "AK");
INSERT INTO City (`name`, `region`) VALUES("Key West", "FL");
INSERT INTO City (`name`, `region`) VALUES("Killeen", "TX");
INSERT INTO City (`name`, `region`) VALUES("Kingman", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Kings Park", "NY");
INSERT INTO City (`name`, `region`) VALUES("Kingsport", "TN");
INSERT INTO City (`name`, `region`) VALUES("Kingston", "MA");
INSERT INTO City (`name`, `region`) VALUES("Kingston", "NY");
INSERT INTO City (`name`, `region`) VALUES("Kirksville", "MO");
INSERT INTO City (`name`, `region`) VALUES("Kissimmee", "FL");
INSERT INTO City (`name`, `region`) VALUES("Klamath Falls", "OR");
INSERT INTO City (`name`, `region`) VALUES("Knoxville", "TN");
INSERT INTO City (`name`, `region`) VALUES("Kodiak", "AK");
INSERT INTO City (`name`, `region`) VALUES("Kokomo", "IN");
INSERT INTO City (`name`, `region`) VALUES("Kyle", "TX");
INSERT INTO City (`name`, `region`) VALUES("La Crosse", "WI");
INSERT INTO City (`name`, `region`) VALUES("La Grange Park", "IL");
INSERT INTO City (`name`, `region`) VALUES("La Mesa", "CA");
INSERT INTO City (`name`, `region`) VALUES("La Porte", "IN");
INSERT INTO City (`name`, `region`) VALUES("La Quinta", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Lacey", "WA");
INSERT INTO City (`name`, `region`) VALUES("Lafayette", "CO");
INSERT INTO City (`name`, `region`) VALUES("Lafayette", "IN");
INSERT INTO City (`name`, `region`) VALUES("Lafayette", "LA");
INSERT INTO City (`name`, `region`) VALUES("Laguna Niguel", "CA");
INSERT INTO City (`name`, `region`) VALUES("Lahaina", "HI");
INSERT INTO City (`name`, `region`) VALUES("Lake Charles", "LA");
INSERT INTO City (`name`, `region`) VALUES("Lake City", "CO");
INSERT INTO City (`name`, `region`) VALUES("Lake City", "FL");
INSERT INTO City (`name`, `region`) VALUES("Lake City", "IA");
INSERT INTO City (`name`, `region`) VALUES("Lake Elsinore", "CA");
INSERT INTO City (`name`, `region`) VALUES("Lake Forest", "CA");
INSERT INTO City (`name`, `region`) VALUES("Lake Geneva", "WI");
INSERT INTO City (`name`, `region`) VALUES("Lake Havasu City", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Lake Orion", "MI");
INSERT INTO City (`name`, `region`) VALUES("Lake Worth", "FL");
INSERT INTO City (`name`, `region`) VALUES("Lakeland", "FL");
INSERT INTO City (`name`, `region`) VALUES("Lakewood", "WA");
INSERT INTO City (`name`, `region`) VALUES("Lancaster", "CA");
INSERT INTO City (`name`, `region`) VALUES("Lancaster", "PA");
INSERT INTO City (`name`, `region`) VALUES("Lander", "WY");
INSERT INTO City (`name`, `region`) VALUES("Lansdale", "PA");
INSERT INTO City (`name`, `region`) VALUES("Lansing", "MI");
INSERT INTO City (`name`, `region`) VALUES("Laramie", "WY");
INSERT INTO City (`name`, `region`) VALUES("Laredo", "TX");
INSERT INTO City (`name`, `region`) VALUES("Largo", "FL");
INSERT INTO City (`name`, `region`) VALUES("Las Cruces", "NM");
INSERT INTO City (`name`, `region`) VALUES("Las Vegas", "NV");
INSERT INTO City (`name`, `region`) VALUES("Laurel", "MD");
INSERT INTO City (`name`, `region`) VALUES("Lawrence", "KS");
INSERT INTO City (`name`, `region`) VALUES("Lawrence", "MA");
INSERT INTO City (`name`, `region`) VALUES("Lawrenceville", "GA");
INSERT INTO City (`name`, `region`) VALUES("Lawton", "OK");
INSERT INTO City (`name`, `region`) VALUES("League City", "TX");
INSERT INTO City (`name`, `region`) VALUES("Leander", "TX");
INSERT INTO City (`name`, `region`) VALUES("Leavenworth", "WA");
INSERT INTO City (`name`, `region`) VALUES("Leawood", "KS");
INSERT INTO City (`name`, `region`) VALUES("Lebanon", "OH");
INSERT INTO City (`name`, `region`) VALUES("Leesburg", "VA");
INSERT INTO City (`name`, `region`) VALUES("Lehi", "UT");
INSERT INTO City (`name`, `region`) VALUES("Leominster", "MA");
INSERT INTO City (`name`, `region`) VALUES("Levittown", "PA");
INSERT INTO City (`name`, `region`) VALUES("Lewis Center", "OH");
INSERT INTO City (`name`, `region`) VALUES("Lewisburg", "PA");
INSERT INTO City (`name`, `region`) VALUES("Lewiston", "ID");
INSERT INTO City (`name`, `region`) VALUES("Lewiston", "ME");
INSERT INTO City (`name`, `region`) VALUES("Lewisville", "TX");
INSERT INTO City (`name`, `region`) VALUES("Lexington Park", "MD");
INSERT INTO City (`name`, `region`) VALUES("Lexington", "KY");
INSERT INTO City (`name`, `region`) VALUES("Libertyville", "IL");
INSERT INTO City (`name`, `region`) VALUES("Lihue", "HI");
INSERT INTO City (`name`, `region`) VALUES("Lima", "OH");
INSERT INTO City (`name`, `region`) VALUES("Lincoln", "NE");
INSERT INTO City (`name`, `region`) VALUES("Lisle", "IL");
INSERT INTO City (`name`, `region`) VALUES("Little Rock", "AR");
INSERT INTO City (`name`, `region`) VALUES("Littleton", "NH");
INSERT INTO City (`name`, `region`) VALUES("Livermore", "CA");
INSERT INTO City (`name`, `region`) VALUES("Livonia", "MI");
INSERT INTO City (`name`, `region`) VALUES("Logan", "UT");
INSERT INTO City (`name`, `region`) VALUES("Lombard", "IL");
INSERT INTO City (`name`, `region`) VALUES("Lompoc", "CA");
INSERT INTO City (`name`, `region`) VALUES("London", "KY");
INSERT INTO City (`name`, `region`) VALUES("London", "OH");
INSERT INTO City (`name`, `region`) VALUES("Long Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Long Branch", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Long Island", "NY");
INSERT INTO City (`name`, `region`) VALUES("Longmeadow", "MA");
INSERT INTO City (`name`, `region`) VALUES("Longmont", "CO");
INSERT INTO City (`name`, `region`) VALUES("Longview", "TX");
INSERT INTO City (`name`, `region`) VALUES("Longview", "WA");
INSERT INTO City (`name`, `region`) VALUES("Lorain", "OH");
INSERT INTO City (`name`, `region`) VALUES("Los Alamos", "NM");
INSERT INTO City (`name`, `region`) VALUES("Los Angeles", "CA");
INSERT INTO City (`name`, `region`) VALUES("Los Gatos", "CA");
INSERT INTO City (`name`, `region`) VALUES("Louisville", "KY");
INSERT INTO City (`name`, `region`) VALUES("Loveland", "CO");
INSERT INTO City (`name`, `region`) VALUES("Lowell", "MA");
INSERT INTO City (`name`, `region`) VALUES("Lubbock", "TX");
INSERT INTO City (`name`, `region`) VALUES("Ludington", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Lufkin", "TX");
INSERT INTO City (`name`, `region`) VALUES("Lunenburg", "MA");
INSERT INTO City (`name`, `region`) VALUES("Lynchburg", "VA");
INSERT INTO City (`name`, `region`) VALUES("Lynden", "WA");
INSERT INTO City (`name`, `region`) VALUES("Lynnwood", "WA");
INSERT INTO City (`name`, `region`) VALUES("Macomb", "MI");
INSERT INTO City (`name`, `region`) VALUES("Macon", "GA");
INSERT INTO City (`name`, `region`) VALUES("Madera", "CA");
INSERT INTO City (`name`, `region`) VALUES("Madison Heights", "MI");
INSERT INTO City (`name`, `region`) VALUES("Madison", "WI");
INSERT INTO City (`name`, `region`) VALUES("Malden", "MA");
INSERT INTO City (`name`, `region`) VALUES("Manassas", "VA");
INSERT INTO City (`name`, `region`) VALUES("Manchester", "NH");
INSERT INTO City (`name`, `region`) VALUES("Manchester", "TN");
INSERT INTO City (`name`, `region`) VALUES("Mandeville", "LA");
INSERT INTO City (`name`, `region`) VALUES("Manhattan Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Manhattan", "KS");
INSERT INTO City (`name`, `region`) VALUES("Manistee", "MI");
INSERT INTO City (`name`, `region`) VALUES("Mankato", "MN");
INSERT INTO City (`name`, `region`) VALUES("Mansfield", "CT");
INSERT INTO City (`name`, `region`) VALUES("Mansfield", "OH");
INSERT INTO City (`name`, `region`) VALUES("Mansfield", "TX");
INSERT INTO City (`name`, `region`) VALUES("Manteca", "CA");
INSERT INTO City (`name`, `region`) VALUES("Maple Valley", "WA");
INSERT INTO City (`name`, `region`) VALUES("Marathon", "FL");
INSERT INTO City (`name`, `region`) VALUES("Marietta", "GA");
INSERT INTO City (`name`, `region`) VALUES("Marina", "CA");
INSERT INTO City (`name`, `region`) VALUES("Marion", "IL");
INSERT INTO City (`name`, `region`) VALUES("Marlborough", "MA");
INSERT INTO City (`name`, `region`) VALUES("Marquette", "MI");
INSERT INTO City (`name`, `region`) VALUES("Marshall", "MI");
INSERT INTO City (`name`, `region`) VALUES("Marshfield", "WI");
INSERT INTO City (`name`, `region`) VALUES("Martha's Vineyard", "MA");
INSERT INTO City (`name`, `region`) VALUES("Martinez", "CA");
INSERT INTO City (`name`, `region`) VALUES("Martinsburg", "WV");
INSERT INTO City (`name`, `region`) VALUES("Martinsville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Mason", "OH");
INSERT INTO City (`name`, `region`) VALUES("Massapequa", "NY");
INSERT INTO City (`name`, `region`) VALUES("Matamoras", "PA");
INSERT INTO City (`name`, `region`) VALUES("Maui", "HI");
INSERT INTO City (`name`, `region`) VALUES("McAlester", "OK");
INSERT INTO City (`name`, `region`) VALUES("McAllen", "TX");
INSERT INTO City (`name`, `region`) VALUES("McHenry", "IL");
INSERT INTO City (`name`, `region`) VALUES("McKinney", "TX");
INSERT INTO City (`name`, `region`) VALUES("McLean", "VA");
INSERT INTO City (`name`, `region`) VALUES("McMinnville", "OR");
INSERT INTO City (`name`, `region`) VALUES("Meadville", "PA");
INSERT INTO City (`name`, `region`) VALUES("Mechanicsburg", "PA");
INSERT INTO City (`name`, `region`) VALUES("Mechanicsville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Medford", "MA");
INSERT INTO City (`name`, `region`) VALUES("Medford", "OR");
INSERT INTO City (`name`, `region`) VALUES("Media", "PA");
INSERT INTO City (`name`, `region`) VALUES("Medina", "OH");
INSERT INTO City (`name`, `region`) VALUES("Melbourne", "AR");
INSERT INTO City (`name`, `region`) VALUES("Melbourne", "FL");
INSERT INTO City (`name`, `region`) VALUES("Memphis", "TN");
INSERT INTO City (`name`, `region`) VALUES("Mena", "AR");
INSERT INTO City (`name`, `region`) VALUES("Menifee", "CA");
INSERT INTO City (`name`, `region`) VALUES("Menominee", "MI");
INSERT INTO City (`name`, `region`) VALUES("Mentor", "OH");
INSERT INTO City (`name`, `region`) VALUES("Merced", "CA");
INSERT INTO City (`name`, `region`) VALUES("Meridian", "MS");
INSERT INTO City (`name`, `region`) VALUES("Merrillville", "IN");
INSERT INTO City (`name`, `region`) VALUES("Mesa", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Mesquite", "NV");
INSERT INTO City (`name`, `region`) VALUES("Mesquite", "TX");
INSERT INTO City (`name`, `region`) VALUES("Miami", "FL");
INSERT INTO City (`name`, `region`) VALUES("Middlesex", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Middletown", "CT");
INSERT INTO City (`name`, `region`) VALUES("Middletown", "DE");
INSERT INTO City (`name`, `region`) VALUES("Middletown", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Midland", "MI");
INSERT INTO City (`name`, `region`) VALUES("Midland", "TX");
INSERT INTO City (`name`, `region`) VALUES("Midlothian", "TX");
INSERT INTO City (`name`, `region`) VALUES("Midlothian", "VA");
INSERT INTO City (`name`, `region`) VALUES("Milford", "PA");
INSERT INTO City (`name`, `region`) VALUES("Milledgeville", "GA");
INSERT INTO City (`name`, `region`) VALUES("Millersburg", "OH");
INSERT INTO City (`name`, `region`) VALUES("Milton", "FL");
INSERT INTO City (`name`, `region`) VALUES("Milwaukee", "WI");
INSERT INTO City (`name`, `region`) VALUES("Minneapolis", "MN");
INSERT INTO City (`name`, `region`) VALUES("Minot", "ND");
INSERT INTO City (`name`, `region`) VALUES("Mission Viejo", "CA");
INSERT INTO City (`name`, `region`) VALUES("Mission", "TX");
INSERT INTO City (`name`, `region`) VALUES("Missoula", "MT");
INSERT INTO City (`name`, `region`) VALUES("Moab", "UT");
INSERT INTO City (`name`, `region`) VALUES("Moberly", "MO");
INSERT INTO City (`name`, `region`) VALUES("Mobile", "AL");
INSERT INTO City (`name`, `region`) VALUES("Modesto", "CA");
INSERT INTO City (`name`, `region`) VALUES("Moline", "IL");
INSERT INTO City (`name`, `region`) VALUES("Moncks Corner", "SC");
INSERT INTO City (`name`, `region`) VALUES("Monroe", "LA");
INSERT INTO City (`name`, `region`) VALUES("Monroe", "MI");
INSERT INTO City (`name`, `region`) VALUES("Monrovia", "CA");
INSERT INTO City (`name`, `region`) VALUES("Montclair", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Monterey Park", "CA");
INSERT INTO City (`name`, `region`) VALUES("Monterey", "CA");
INSERT INTO City (`name`, `region`) VALUES("Montgomery", "AL");
INSERT INTO City (`name`, `region`) VALUES("Montpelier", "VT");
INSERT INTO City (`name`, `region`) VALUES("Montross", "VA");
INSERT INTO City (`name`, `region`) VALUES("Monument", "CO");
INSERT INTO City (`name`, `region`) VALUES("Mooresville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Morehead", "KY");
INSERT INTO City (`name`, `region`) VALUES("Morgan City", "LA");
INSERT INTO City (`name`, `region`) VALUES("Morgantown", "WV");
INSERT INTO City (`name`, `region`) VALUES("Morristown", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Morristown", "TN");
INSERT INTO City (`name`, `region`) VALUES("Morrisville", "NC");
INSERT INTO City (`name`, `region`) VALUES("Morrisville", "PA");
INSERT INTO City (`name`, `region`) VALUES("Moscow", "ID");
INSERT INTO City (`name`, `region`) VALUES("Moses Lake", "WA");
INSERT INTO City (`name`, `region`) VALUES("Moss Point", "MS");
INSERT INTO City (`name`, `region`) VALUES("Moultrie", "GA");
INSERT INTO City (`name`, `region`) VALUES("Mount Pleasant", "MI");
INSERT INTO City (`name`, `region`) VALUES("Mount Vernon", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Mount Vernon", "NY");
INSERT INTO City (`name`, `region`) VALUES("Mount Vernon", "WA");
INSERT INTO City (`name`, `region`) VALUES("Mountain Home", "AR");
INSERT INTO City (`name`, `region`) VALUES("Mountain View", "CA");
INSERT INTO City (`name`, `region`) VALUES("Muncie", "IN");
INSERT INTO City (`name`, `region`) VALUES("Mundelein", "IL");
INSERT INTO City (`name`, `region`) VALUES("Murfreesboro", "TN");
INSERT INTO City (`name`, `region`) VALUES("Murrieta", "CA");
INSERT INTO City (`name`, `region`) VALUES("Muscatine", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Muskegon", "MI");
INSERT INTO City (`name`, `region`) VALUES("Muskogee", "OK");
INSERT INTO City (`name`, `region`) VALUES("Myrtle Beach", "SC");
INSERT INTO City (`name`, `region`) VALUES("Nacogdoches", "TX");
INSERT INTO City (`name`, `region`) VALUES("Nampa", "ID");
INSERT INTO City (`name`, `region`) VALUES("Napa", "CA");
INSERT INTO City (`name`, `region`) VALUES("Naperville", "IL");
INSERT INTO City (`name`, `region`) VALUES("Naples", "FL");
INSERT INTO City (`name`, `region`) VALUES("Nashua", "NH");
INSERT INTO City (`name`, `region`) VALUES("Nashville", "TN");
INSERT INTO City (`name`, `region`) VALUES("Natick", "MA");
INSERT INTO City (`name`, `region`) VALUES("Neenah", "WI");
INSERT INTO City (`name`, `region`) VALUES("Neillsville", "WI");
INSERT INTO City (`name`, `region`) VALUES("New Albany", "OH");
INSERT INTO City (`name`, `region`) VALUES("New Bedford", "MA");
INSERT INTO City (`name`, `region`) VALUES("New Bern", "NC");
INSERT INTO City (`name`, `region`) VALUES("New Braunfels", "TX");
INSERT INTO City (`name`, `region`) VALUES("New Castle", "DE");
INSERT INTO City (`name`, `region`) VALUES("New Castle", "PA");
INSERT INTO City (`name`, `region`) VALUES("New City", "NY");
INSERT INTO City (`name`, `region`) VALUES("New Haven", "CT");
INSERT INTO City (`name`, `region`) VALUES("New Orleans", "LA");
INSERT INTO City (`name`, `region`) VALUES("New Paltz", "NY");
INSERT INTO City (`name`, `region`) VALUES("New Port Richey", "FL");
INSERT INTO City (`name`, `region`) VALUES("New Rochelle", "NY");
INSERT INTO City (`name`, `region`) VALUES("New Smyrna Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("New Windsor", "NY");
INSERT INTO City (`name`, `region`) VALUES("New York", "NY");
INSERT INTO City (`name`, `region`) VALUES("Newark", "DE");
INSERT INTO City (`name`, `region`) VALUES("Newark", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Newnan", "GA");
INSERT INTO City (`name`, `region`) VALUES("Newport Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Newport News", "VA");
INSERT INTO City (`name`, `region`) VALUES("Newport", "OR");
INSERT INTO City (`name`, `region`) VALUES("Newport", "RI");
INSERT INTO City (`name`, `region`) VALUES("Newton Falls", "OH");
INSERT INTO City (`name`, `region`) VALUES("Newton", "MA");
INSERT INTO City (`name`, `region`) VALUES("Newton", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Niagara Falls", "NY");
INSERT INTO City (`name`, `region`) VALUES("Niantic", "CT");
INSERT INTO City (`name`, `region`) VALUES("Niceville FL,", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Niles", "MI");
INSERT INTO City (`name`, `region`) VALUES("Ninilchik", "AK");
INSERT INTO City (`name`, `region`) VALUES("Nogales", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Nome", "AK");
INSERT INTO City (`name`, `region`) VALUES("Norcross", "GA");
INSERT INTO City (`name`, `region`) VALUES("Norfolk", "VA");
INSERT INTO City (`name`, `region`) VALUES("Normal", "IL");
INSERT INTO City (`name`, `region`) VALUES("Norman", "OK");
INSERT INTO City (`name`, `region`) VALUES("North Bend", "WA");
INSERT INTO City (`name`, `region`) VALUES("North Brunswick", "NJ");
INSERT INTO City (`name`, `region`) VALUES("North Charleston", "SC");
INSERT INTO City (`name`, `region`) VALUES("North East", "MD");
INSERT INTO City (`name`, `region`) VALUES("North Platte", "NE");
INSERT INTO City (`name`, `region`) VALUES("Northampton", "MA");
INSERT INTO City (`name`, `region`) VALUES("Northfield", "MN");
INSERT INTO City (`name`, `region`) VALUES("Norwalk", "CA");
INSERT INTO City (`name`, `region`) VALUES("Norwalk", "CT");
INSERT INTO City (`name`, `region`) VALUES("Norwich", "CT");
INSERT INTO City (`name`, `region`) VALUES("Norwich", "NY");
INSERT INTO City (`name`, `region`) VALUES("Novi", "MI");
INSERT INTO City (`name`, `region`) VALUES("Nyack", "NY");
INSERT INTO City (`name`, `region`) VALUES("O'Fallon", "IL");
INSERT INTO City (`name`, `region`) VALUES("O'Fallon", "MO");
INSERT INTO City (`name`, `region`) VALUES("Oak Harbor", "WA");
INSERT INTO City (`name`, `region`) VALUES("Oak Park", "IL");
INSERT INTO City (`name`, `region`) VALUES("Oak Ridge", "TN");
INSERT INTO City (`name`, `region`) VALUES("Oakland", "CA");
INSERT INTO City (`name`, `region`) VALUES("Oakland", "TN");
INSERT INTO City (`name`, `region`) VALUES("Ocala", "FL");
INSERT INTO City (`name`, `region`) VALUES("Ocean Shores", "WA");
INSERT INTO City (`name`, `region`) VALUES("Ocean Springs", "MI");
INSERT INTO City (`name`, `region`) VALUES("Oceanside", "CA");
INSERT INTO City (`name`, `region`) VALUES("Odessa", "TX");
INSERT INTO City (`name`, `region`) VALUES("Ogden", "UT");
INSERT INTO City (`name`, `region`) VALUES("Ojai", "CA");
INSERT INTO City (`name`, `region`) VALUES("Oklahoma City", "OK");
INSERT INTO City (`name`, `region`) VALUES("Old Bridge", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Olympia", "WA");
INSERT INTO City (`name`, `region`) VALUES("Omaha", "NE");
INSERT INTO City (`name`, `region`) VALUES("Ontario,CA", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Orem", "UT");
INSERT INTO City (`name`, `region`) VALUES("Orlando", "FL");
INSERT INTO City (`name`, `region`) VALUES("Oroville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Oshkosh", "WI");
INSERT INTO City (`name`, `region`) VALUES("Oswego", "NY");
INSERT INTO City (`name`, `region`) VALUES("Otsego", "MN");
INSERT INTO City (`name`, `region`) VALUES("Ottawa", "Illinois");
INSERT INTO City (`name`, `region`) VALUES("Ottumwa", "IA");
INSERT INTO City (`name`, `region`) VALUES("Overland Park", "KS");
INSERT INTO City (`name`, `region`) VALUES("Owensboro", "KY");
INSERT INTO City (`name`, `region`) VALUES("Owings Mills", "MD");
INSERT INTO City (`name`, `region`) VALUES("Owosso", "MI");
INSERT INTO City (`name`, `region`) VALUES("Oxford", "MS");
INSERT INTO City (`name`, `region`) VALUES("Oxnard", "CA");
INSERT INTO City (`name`, `region`) VALUES("Oyster Bay", "NY");
INSERT INTO City (`name`, `region`) VALUES("Paducah", "KY");
INSERT INTO City (`name`, `region`) VALUES("Pagosa Springs", "CO");
INSERT INTO City (`name`, `region`) VALUES("Pahrump", "NV");
INSERT INTO City (`name`, `region`) VALUES("Palatine", "IL");
INSERT INTO City (`name`, `region`) VALUES("Palatka", "FL");
INSERT INTO City (`name`, `region`) VALUES("Palestine", "TX");
INSERT INTO City (`name`, `region`) VALUES("Palm Bay", "FL");
INSERT INTO City (`name`, `region`) VALUES("Palm Coast", "FL");
INSERT INTO City (`name`, `region`) VALUES("Palm Springs", "CA");
INSERT INTO City (`name`, `region`) VALUES("Palmdale", "CA");
INSERT INTO City (`name`, `region`) VALUES("Palmer", "AK");
INSERT INTO City (`name`, `region`) VALUES("Palo Alto", "CA");
INSERT INTO City (`name`, `region`) VALUES("Panama City", "FL");
INSERT INTO City (`name`, `region`) VALUES("Paola", "KS");
INSERT INTO City (`name`, `region`) VALUES("Paradise", "CA");
INSERT INTO City (`name`, `region`) VALUES("Paris", "TX");
INSERT INTO City (`name`, `region`) VALUES("Park City", "UT");
INSERT INTO City (`name`, `region`) VALUES("Parkersburg", "WV");
INSERT INTO City (`name`, `region`) VALUES("Parma", "OH");
INSERT INTO City (`name`, `region`) VALUES("Parsippany-Troy Hills", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Pasadena", "CA");
INSERT INTO City (`name`, `region`) VALUES("Pasco", "WA");
INSERT INTO City (`name`, `region`) VALUES("Paso Robles", "CA");
INSERT INTO City (`name`, `region`) VALUES("Passaic", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Paterson", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Pawtucket", "RI");
INSERT INTO City (`name`, `region`) VALUES("Payson", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Payson", "UT");
INSERT INTO City (`name`, `region`) VALUES("Peachtree City", "GA");
INSERT INTO City (`name`, `region`) VALUES("Pearl City", "HI");
INSERT INTO City (`name`, `region`) VALUES("Pembroke Pines", "FL");
INSERT INTO City (`name`, `region`) VALUES("Pendleton", "OR");
INSERT INTO City (`name`, `region`) VALUES("Pensacola", "FL");
INSERT INTO City (`name`, `region`) VALUES("Peoria", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Peoria", "IL");
INSERT INTO City (`name`, `region`) VALUES("Perkasie", "PA");
INSERT INTO City (`name`, `region`) VALUES("Perrysburg", "OH");
INSERT INTO City (`name`, `region`) VALUES("Petaluma", "CA");
INSERT INTO City (`name`, `region`) VALUES("Petoskey", "MI");
INSERT INTO City (`name`, `region`) VALUES("Philadelphia", "PA");
INSERT INTO City (`name`, `region`) VALUES("Phillipsburg", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Phoenix", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Piedmont", "CA");
INSERT INTO City (`name`, `region`) VALUES("Pierre", "SD");
INSERT INTO City (`name`, `region`) VALUES("Pikeville", "KY");
INSERT INTO City (`name`, `region`) VALUES("Pinehurst", "NC");
INSERT INTO City (`name`, `region`) VALUES("Pinellas Park", "FL");
INSERT INTO City (`name`, `region`) VALUES("Pinetop-Lakeside", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Piscataway", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Pittsburgh", "PA");
INSERT INTO City (`name`, `region`) VALUES("Pittsfield", "MA");
INSERT INTO City (`name`, `region`) VALUES("Plainfield", "IL");
INSERT INTO City (`name`, `region`) VALUES("Plano", "TX");
INSERT INTO City (`name`, `region`) VALUES("Plantation", "FL");
INSERT INTO City (`name`, `region`) VALUES("Plattsburgh", "NY");
INSERT INTO City (`name`, `region`) VALUES("Pleasant Hill", "CA");
INSERT INTO City (`name`, `region`) VALUES("Pleasanton", "CA");
INSERT INTO City (`name`, `region`) VALUES("Pleasantville", "NY");
INSERT INTO City (`name`, `region`) VALUES("Plymouth", "MI");
INSERT INTO City (`name`, `region`) VALUES("Pocatello", "ID");
INSERT INTO City (`name`, `region`) VALUES("Polson", "MT");
INSERT INTO City (`name`, `region`) VALUES("Pomona", "CA");
INSERT INTO City (`name`, `region`) VALUES("Ponca City", "OK");
INSERT INTO City (`name`, `region`) VALUES("Pontiac", "MI");
INSERT INTO City (`name`, `region`) VALUES("Pontotoc", "MS");
INSERT INTO City (`name`, `region`) VALUES("Pooler", "GA");
INSERT INTO City (`name`, `region`) VALUES("Port Angeles", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Port Hadlock", "WA");
INSERT INTO City (`name`, `region`) VALUES("Port Huron", "MI");
INSERT INTO City (`name`, `region`) VALUES("Port Jefferson Station", "NY");
INSERT INTO City (`name`, `region`) VALUES("Port St Lucie", "FL");
INSERT INTO City (`name`, `region`) VALUES("Porter Ranch", "CA");
INSERT INTO City (`name`, `region`) VALUES("Portland", "ME");
INSERT INTO City (`name`, `region`) VALUES("Portland", "OR");
INSERT INTO City (`name`, `region`) VALUES("Portsmouth", "NH");
INSERT INTO City (`name`, `region`) VALUES("Portsmouth", "OH");
INSERT INTO City (`name`, `region`) VALUES("Pottsville", "PA");
INSERT INTO City (`name`, `region`) VALUES("Poughkeepsie", "NY");
INSERT INTO City (`name`, `region`) VALUES("Poulsbo", "WA");
INSERT INTO City (`name`, `region`) VALUES("Prattville", "AL");
INSERT INTO City (`name`, `region`) VALUES("Prescott", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Presque Isle", "ME");
INSERT INTO City (`name`, `region`) VALUES("Princeton", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Providence", "RI");
INSERT INTO City (`name`, `region`) VALUES("Pueblo", "CO");
INSERT INTO City (`name`, `region`) VALUES("Pukalani", "HI");
INSERT INTO City (`name`, `region`) VALUES("Pullman", "WA");
INSERT INTO City (`name`, `region`) VALUES("Purcellville", "VA");
INSERT INTO City (`name`, `region`) VALUES("Putnam", "CT");
INSERT INTO City (`name`, `region`) VALUES("Puyallup", "WA");
INSERT INTO City (`name`, `region`) VALUES("Queen Creek", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Queens", "NY");
INSERT INTO City (`name`, `region`) VALUES("Queensbury", "NY");
INSERT INTO City (`name`, `region`) VALUES("Quincy", "IL");
INSERT INTO City (`name`, `region`) VALUES("Quincy", "MA");
INSERT INTO City (`name`, `region`) VALUES("Raleigh", "NC");
INSERT INTO City (`name`, `region`) VALUES("Ramsey", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Rancho Cucamonga", "CA");
INSERT INTO City (`name`, `region`) VALUES("Rancho Palos Verdes", "CA");
INSERT INTO City (`name`, `region`) VALUES("Rancho Santa Margarita", "CA");
INSERT INTO City (`name`, `region`) VALUES("Rapid City", "SD");
INSERT INTO City (`name`, `region`) VALUES("Reading", "PA");
INSERT INTO City (`name`, `region`) VALUES("Red Bank", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Redding", "CA");
INSERT INTO City (`name`, `region`) VALUES("Redlands", "CA");
INSERT INTO City (`name`, `region`) VALUES("Redmond", "WA");
INSERT INTO City (`name`, `region`) VALUES("Redondo Beach", "CA");
INSERT INTO City (`name`, `region`) VALUES("Redwood City", "CA");
INSERT INTO City (`name`, `region`) VALUES("Rehoboth Beach", "DE");
INSERT INTO City (`name`, `region`) VALUES("Reno", "NV");
INSERT INTO City (`name`, `region`) VALUES("Renton", "WA");
INSERT INTO City (`name`, `region`) VALUES("Reston", "VA");
INSERT INTO City (`name`, `region`) VALUES("Rhinelander", "WI");
INSERT INTO City (`name`, `region`) VALUES("Rice Lake", "WI");
INSERT INTO City (`name`, `region`) VALUES("Richland", "WA");
INSERT INTO City (`name`, `region`) VALUES("Richmond", "KY");
INSERT INTO City (`name`, `region`) VALUES("Richmond", "VA");
INSERT INTO City (`name`, `region`) VALUES("Ridgecrest", "CA");
INSERT INTO City (`name`, `region`) VALUES("Ridgefield", "CT");
INSERT INTO City (`name`, `region`) VALUES("Ridgewood", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Rincon", "GA");
INSERT INTO City (`name`, `region`) VALUES("Rio Rancho", "NM");
INSERT INTO City (`name`, `region`) VALUES("River Falls", "WI");
INSERT INTO City (`name`, `region`) VALUES("Riverside", "CA");
INSERT INTO City (`name`, `region`) VALUES("Riverton", "UT");
INSERT INTO City (`name`, `region`) VALUES("Roanoke", "VA");
INSERT INTO City (`name`, `region`) VALUES("Robinson", "IL");
INSERT INTO City (`name`, `region`) VALUES("Rochester", "MI");
INSERT INTO City (`name`, `region`) VALUES("Rochester", "MN");
INSERT INTO City (`name`, `region`) VALUES("Rochester", "NY");
INSERT INTO City (`name`, `region`) VALUES("Rock Hill", "SC");
INSERT INTO City (`name`, `region`) VALUES("Rock Island", "IL");
INSERT INTO City (`name`, `region`) VALUES("Rock Springs", "WY");
INSERT INTO City (`name`, `region`) VALUES("Rockford", "IL");
INSERT INTO City (`name`, `region`) VALUES("Rockford", "MI");
INSERT INTO City (`name`, `region`) VALUES("Rocklin", "CA");
INSERT INTO City (`name`, `region`) VALUES("Rockville", "MD");
INSERT INTO City (`name`, `region`) VALUES("Rockwall", "TX");
INSERT INTO City (`name`, `region`) VALUES("Rocky Hill", "CT");
INSERT INTO City (`name`, `region`) VALUES("Rocky Mount", "NC");
INSERT INTO City (`name`, `region`) VALUES("Rogers", "AR");
INSERT INTO City (`name`, `region`) VALUES("Rolla", "MO");
INSERT INTO City (`name`, `region`) VALUES("Rome", "GA");
INSERT INTO City (`name`, `region`) VALUES("Ronkonkoma", "NY");
INSERT INTO City (`name`, `region`) VALUES("Roseburg", "OR");
INSERT INTO City (`name`, `region`) VALUES("Roseville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Round Rock", "TX");
INSERT INTO City (`name`, `region`) VALUES("Roy", "UT");
INSERT INTO City (`name`, `region`) VALUES("Royal Oak", "MI");
INSERT INTO City (`name`, `region`) VALUES("Royersford", "PA");
INSERT INTO City (`name`, `region`) VALUES("Russellville", "AR");
INSERT INTO City (`name`, `region`) VALUES("Rutherford", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Rutland", "VT");
INSERT INTO City (`name`, `region`) VALUES("Sacramento", "CA");
INSERT INTO City (`name`, `region`) VALUES("Safety Harbor", "FL");
INSERT INTO City (`name`, `region`) VALUES("Saginaw", "MI");
INSERT INTO City (`name`, `region`) VALUES("Saint Albans", "VT");
INSERT INTO City (`name`, `region`) VALUES("Saint Charles", "IL");
INSERT INTO City (`name`, `region`) VALUES("Saint Charles", "MO");
INSERT INTO City (`name`, `region`) VALUES("Saint Cloud", "MN");
INSERT INTO City (`name`, `region`) VALUES("Saint George", "UT");
INSERT INTO City (`name`, `region`) VALUES("Saint Johns", "MI");
INSERT INTO City (`name`, `region`) VALUES("Saint Joseph", "MI");
INSERT INTO City (`name`, `region`) VALUES("Saint Joseph", "MO");
INSERT INTO City (`name`, `region`) VALUES("Saint Louis", "MO");
INSERT INTO City (`name`, `region`) VALUES("Saint Paul", "MN");
INSERT INTO City (`name`, `region`) VALUES("Saint Petersburg", "FL");
INSERT INTO City (`name`, `region`) VALUES("Salem", "MA");
INSERT INTO City (`name`, `region`) VALUES("Salem", "OH");
INSERT INTO City (`name`, `region`) VALUES("Salem", "OR");
INSERT INTO City (`name`, `region`) VALUES("Salina", "KS");
INSERT INTO City (`name`, `region`) VALUES("Salinas", "CA");
INSERT INTO City (`name`, `region`) VALUES("Salisbury", "MD");
INSERT INTO City (`name`, `region`) VALUES("Salt Lake City", "UT");
INSERT INTO City (`name`, `region`) VALUES("San Angelo", "TX");
INSERT INTO City (`name`, `region`) VALUES("San Antonio", "TX");
INSERT INTO City (`name`, `region`) VALUES("San Bernardino", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Clemente", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Diego", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Dimas", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Francisco", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Jose", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Leandro", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Luis Obispo", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Marcos", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Marcos", "TX");
INSERT INTO City (`name`, `region`) VALUES("San Mateo", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Rafael", "CA");
INSERT INTO City (`name`, `region`) VALUES("San Ramon", "CA");
INSERT INTO City (`name`, `region`) VALUES("Sandpoint", "ID");
INSERT INTO City (`name`, `region`) VALUES("Sandusky", "OH");
INSERT INTO City (`name`, `region`) VALUES("Sanford", "NC");
INSERT INTO City (`name`, `region`) VALUES("Santa Ana", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Barbara", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Clara", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Clarita", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Cruz", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Fe", "NM");
INSERT INTO City (`name`, `region`) VALUES("Santa Maria", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Monica", "CA");
INSERT INTO City (`name`, `region`) VALUES("Santa Rosa", "CA");
INSERT INTO City (`name`, `region`) VALUES("Sarasota", "FL");
INSERT INTO City (`name`, `region`) VALUES("Saratoga Springs", "NY");
INSERT INTO City (`name`, `region`) VALUES("Saratoga", "CA");
INSERT INTO City (`name`, `region`) VALUES("Satellite Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Savannah", "GA");
INSERT INTO City (`name`, `region`) VALUES("Sayreville", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Schaumburg", "IL");
INSERT INTO City (`name`, `region`) VALUES("Schenectady", "NY");
INSERT INTO City (`name`, `region`) VALUES("Scottsbluff", "NE");
INSERT INTO City (`name`, `region`) VALUES("Scottsdale", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Scottsville", "KY");
INSERT INTO City (`name`, `region`) VALUES("Scranton", "PA");
INSERT INTO City (`name`, `region`) VALUES("SeaTac", "WA");
INSERT INTO City (`name`, `region`) VALUES("Seaside", "OR");
INSERT INTO City (`name`, `region`) VALUES("Seattle", "WA");
INSERT INTO City (`name`, `region`) VALUES("Sebring", "FL");
INSERT INTO City (`name`, `region`) VALUES("Sedalia", "MO");
INSERT INTO City (`name`, `region`) VALUES("Seekonk", "MA");
INSERT INTO City (`name`, `region`) VALUES("Selden", "NY");
INSERT INTO City (`name`, `region`) VALUES("Seminole", "FL");
INSERT INTO City (`name`, `region`) VALUES("Sequim", "WA");
INSERT INTO City (`name`, `region`) VALUES("Severn", "MD");
INSERT INTO City (`name`, `region`) VALUES("Severna Park", "MD");
INSERT INTO City (`name`, `region`) VALUES("Sevierville", "TN");
INSERT INTO City (`name`, `region`) VALUES("Shawnee", "OK");
INSERT INTO City (`name`, `region`) VALUES("Sheboygan", "WI");
INSERT INTO City (`name`, `region`) VALUES("Shelby Township", "MI");
INSERT INTO City (`name`, `region`) VALUES("Shelby", "NC");
INSERT INTO City (`name`, `region`) VALUES("Sheldon", "IA");
INSERT INTO City (`name`, `region`) VALUES("Sheridan", "WY");
INSERT INTO City (`name`, `region`) VALUES("Sherman", "TX");
INSERT INTO City (`name`, `region`) VALUES("Shoreline", "WA");
INSERT INTO City (`name`, `region`) VALUES("Shreveport", "LA");
INSERT INTO City (`name`, `region`) VALUES("Sicklerville", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Sidney", "NE");
INSERT INTO City (`name`, `region`) VALUES("Sierra Vista", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Silver City", "NM");
INSERT INTO City (`name`, `region`) VALUES("Silver Spring", "MD");
INSERT INTO City (`name`, `region`) VALUES("Simi Valley", "CA");
INSERT INTO City (`name`, `region`) VALUES("Simpsonville", "SC");
INSERT INTO City (`name`, `region`) VALUES("Sioux City", "IA");
INSERT INTO City (`name`, `region`) VALUES("Sioux Falls", "SD");
INSERT INTO City (`name`, `region`) VALUES("Sitka", "AK");
INSERT INTO City (`name`, `region`) VALUES("Slidell", "LA");
INSERT INTO City (`name`, `region`) VALUES("Smithtown", "NY");
INSERT INTO City (`name`, `region`) VALUES("Smyrna", "GA");
INSERT INTO City (`name`, `region`) VALUES("Somerset", "KY");
INSERT INTO City (`name`, `region`) VALUES("Somerset", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Somerville", "MA");
INSERT INTO City (`name`, `region`) VALUES("Sonora", "CA");
INSERT INTO City (`name`, `region`) VALUES("South Bend", "IN");
INSERT INTO City (`name`, `region`) VALUES("South Riding", "VA");
INSERT INTO City (`name`, `region`) VALUES("Southampton", "NY");
INSERT INTO City (`name`, `region`) VALUES("Southaven", "MS");
INSERT INTO City (`name`, `region`) VALUES("Southbridge", "MA");
INSERT INTO City (`name`, `region`) VALUES("Southfield", "MI");
INSERT INTO City (`name`, `region`) VALUES("Spanaway", "WA");
INSERT INTO City (`name`, `region`) VALUES("Spanish Fork", "UT");
INSERT INTO City (`name`, `region`) VALUES("Spartanburg", "SC");
INSERT INTO City (`name`, `region`) VALUES("Spearfish", "SD");
INSERT INTO City (`name`, `region`) VALUES("Spokane", "WA");
INSERT INTO City (`name`, `region`) VALUES("Spring Hill", "FL");
INSERT INTO City (`name`, `region`) VALUES("Spring Hill", "TN");
INSERT INTO City (`name`, `region`) VALUES("Spring Valley", "IL");
INSERT INTO City (`name`, `region`) VALUES("Spring Valley", "NY");
INSERT INTO City (`name`, `region`) VALUES("Spring", "TX");
INSERT INTO City (`name`, `region`) VALUES("Springfield", "IL");
INSERT INTO City (`name`, `region`) VALUES("Springfield", "MA");
INSERT INTO City (`name`, `region`) VALUES("Springfield", "MO");
INSERT INTO City (`name`, `region`) VALUES("Springfield", "OH");
INSERT INTO City (`name`, `region`) VALUES("Springfield", "OR");
INSERT INTO City (`name`, `region`) VALUES("Springfield", "VA");
INSERT INTO City (`name`, `region`) VALUES("Spruce Pine", "NC");
INSERT INTO City (`name`, `region`) VALUES("St Marys", "GA");
INSERT INTO City (`name`, `region`) VALUES("St. Augustine", "FL");
INSERT INTO City (`name`, `region`) VALUES("Stamford", "CT");
INSERT INTO City (`name`, `region`) VALUES("Stanford", "CA");
INSERT INTO City (`name`, `region`) VALUES("Starkville", "MS");
INSERT INTO City (`name`, `region`) VALUES("State College", "PA");
INSERT INTO City (`name`, `region`) VALUES("Staten Island", "NY");
INSERT INTO City (`name`, `region`) VALUES("Statesboro", "GA");
INSERT INTO City (`name`, `region`) VALUES("Staunton", "VA");
INSERT INTO City (`name`, `region`) VALUES("Sterling", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Sterling Heights", "MI");
INSERT INTO City (`name`, `region`) VALUES("Stevens Point", "WI");
INSERT INTO City (`name`, `region`) VALUES("Stillwater", "MN");
INSERT INTO City (`name`, `region`) VALUES("Stillwater", "OK");
INSERT INTO City (`name`, `region`) VALUES("Stockton", "CA");
INSERT INTO City (`name`, `region`) VALUES("Stone Mountain", "GA");
INSERT INTO City (`name`, `region`) VALUES("Streamwood", "IL");
INSERT INTO City (`name`, `region`) VALUES("Streestboro", "OH");
INSERT INTO City (`name`, `region`) VALUES("Stroudsburg", "PA");
INSERT INTO City (`name`, `region`) VALUES("Stuart", "FL");
INSERT INTO City (`name`, `region`) VALUES("Suffolk", "VA");
INSERT INTO City (`name`, `region`) VALUES("Sugar Land", "TX");
INSERT INTO City (`name`, `region`) VALUES("Summerville", "SC");
INSERT INTO City (`name`, `region`) VALUES("Summit", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Sumter", "SC");
INSERT INTO City (`name`, `region`) VALUES("Sun City Center", "FL");
INSERT INTO City (`name`, `region`) VALUES("Sunbury", "PA");
INSERT INTO City (`name`, `region`) VALUES("Sunny Isles Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Sunnyvale", "CA");
INSERT INTO City (`name`, `region`) VALUES("Sunrise", "FL");
INSERT INTO City (`name`, `region`) VALUES("Superior", "WI");
INSERT INTO City (`name`, `region`) VALUES("Surprise", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Susanville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Suwanee", "GA");
INSERT INTO City (`name`, `region`) VALUES("Sylva", "NC");
INSERT INTO City (`name`, `region`) VALUES("Sylvania", "OH");
INSERT INTO City (`name`, `region`) VALUES("Syracuse", "NY");
INSERT INTO City (`name`, `region`) VALUES("Tacoma", "WA");
INSERT INTO City (`name`, `region`) VALUES("Tallahassee", "FL");
INSERT INTO City (`name`, `region`) VALUES("Tampa", "FL");
INSERT INTO City (`name`, `region`) VALUES("Taos", "NM");
INSERT INTO City (`name`, `region`) VALUES("Taunton", "MA");
INSERT INTO City (`name`, `region`) VALUES("Taylor", "TX");
INSERT INTO City (`name`, `region`) VALUES("Teaneck", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Tega Cay", "SC");
INSERT INTO City (`name`, `region`) VALUES("Tehachapi", "CA");
INSERT INTO City (`name`, `region`) VALUES("Tell City", "IN");
INSERT INTO City (`name`, `region`) VALUES("Temecula", "CA");
INSERT INTO City (`name`, `region`) VALUES("Tempe", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Temple Hills", "MD");
INSERT INTO City (`name`, `region`) VALUES("Temple", "TX");
INSERT INTO City (`name`, `region`) VALUES("Terre Haute", "IN");
INSERT INTO City (`name`, `region`) VALUES("Texarkana", "AR");
INSERT INTO City (`name`, `region`) VALUES("Texarkana", "TX");
INSERT INTO City (`name`, `region`) VALUES("Texas City", "TX");
INSERT INTO City (`name`, `region`) VALUES("The Dalles", "OR");
INSERT INTO City (`name`, `region`) VALUES("The Villages", "FL");
INSERT INTO City (`name`, `region`) VALUES("The Woodlands", "TX");
INSERT INTO City (`name`, `region`) VALUES("Thomasville", "GA");
INSERT INTO City (`name`, `region`) VALUES("Thornton", "CO");
INSERT INTO City (`name`, `region`) VALUES("Thousand Oaks", "CA");
INSERT INTO City (`name`, `region`) VALUES("Tiffin", "OH");
INSERT INTO City (`name`, `region`) VALUES("Tipp City", "OH");
INSERT INTO City (`name`, `region`) VALUES("Titusville", "FL");
INSERT INTO City (`name`, `region`) VALUES("Toledo", "OH");
INSERT INTO City (`name`, `region`) VALUES("Tomball TX", "undefined");
INSERT INTO City (`name`, `region`) VALUES("Toms River", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Tooele", "UT");
INSERT INTO City (`name`, `region`) VALUES("Topeka", "KS");
INSERT INTO City (`name`, `region`) VALUES("Torrance", "CA");
INSERT INTO City (`name`, `region`) VALUES("Torrington", "CT");
INSERT INTO City (`name`, `region`) VALUES("Tracy", "CA");
INSERT INTO City (`name`, `region`) VALUES("Traverse City", "MI");
INSERT INTO City (`name`, `region`) VALUES("Trenton", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Troy", "AL");
INSERT INTO City (`name`, `region`) VALUES("Troy", "MI");
INSERT INTO City (`name`, `region`) VALUES("Troy", "NY");
INSERT INTO City (`name`, `region`) VALUES("Truckee", "CA");
INSERT INTO City (`name`, `region`) VALUES("Trumbull", "CT");
INSERT INTO City (`name`, `region`) VALUES("Tualtin", " OR");
INSERT INTO City (`name`, `region`) VALUES("Tucson", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Tulare", "CA");
INSERT INTO City (`name`, `region`) VALUES("Tullahoma", "TN");
INSERT INTO City (`name`, `region`) VALUES("Tulsa", "OK");
INSERT INTO City (`name`, `region`) VALUES("Tupelo", "MS");
INSERT INTO City (`name`, `region`) VALUES("Turlock", "CA");
INSERT INTO City (`name`, `region`) VALUES("Tuscaloosa", "AL");
INSERT INTO City (`name`, `region`) VALUES("Tustin", "CA");
INSERT INTO City (`name`, `region`) VALUES("Twin Falls", "ID");
INSERT INTO City (`name`, `region`) VALUES("Tyler", "TX");
INSERT INTO City (`name`, `region`) VALUES("Union City", "TN");
INSERT INTO City (`name`, `region`) VALUES("Uniondale", "NY");
INSERT INTO City (`name`, `region`) VALUES("Upland", "CA");
INSERT INTO City (`name`, `region`) VALUES("Urbana", "IL");
INSERT INTO City (`name`, `region`) VALUES("Utica", "NY");
INSERT INTO City (`name`, `region`) VALUES("Vacaville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Valdosta", "GA");
INSERT INTO City (`name`, `region`) VALUES("Vallejo", "CA");
INSERT INTO City (`name`, `region`) VALUES("Valparaiso", "IN");
INSERT INTO City (`name`, `region`) VALUES("Van Wert", "OH");
INSERT INTO City (`name`, `region`) VALUES("Vancouver", "WA");
INSERT INTO City (`name`, `region`) VALUES("Venice", "FL");
INSERT INTO City (`name`, `region`) VALUES("Ventura", "CA");
INSERT INTO City (`name`, `region`) VALUES("Vero Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("Versailles", "KY");
INSERT INTO City (`name`, `region`) VALUES("Victoria", "TX");
INSERT INTO City (`name`, `region`) VALUES("Victorville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Virginia Beach", "VA");
INSERT INTO City (`name`, `region`) VALUES("Visalia", "CA");
INSERT INTO City (`name`, `region`) VALUES("Vista", "CA");
INSERT INTO City (`name`, `region`) VALUES("Waccabuc", "NY");
INSERT INTO City (`name`, `region`) VALUES("Waco", "TX");
INSERT INTO City (`name`, `region`) VALUES("Wadsworth", "OH");
INSERT INTO City (`name`, `region`) VALUES("Waikiki", "HI");
INSERT INTO City (`name`, `region`) VALUES("Wailuku", "HI");
INSERT INTO City (`name`, `region`) VALUES("Waipahu", "HI");
INSERT INTO City (`name`, `region`) VALUES("Wakefield", "MA");
INSERT INTO City (`name`, `region`) VALUES("Wakefield-Peacedale", "RI");
INSERT INTO City (`name`, `region`) VALUES("Waldorf", "MD");
INSERT INTO City (`name`, `region`) VALUES("Walla Walla", "WA");
INSERT INTO City (`name`, `region`) VALUES("Wallingford", "CT");
INSERT INTO City (`name`, `region`) VALUES("Walnut Creek", "CA");
INSERT INTO City (`name`, `region`) VALUES("Walnut", "CA");
INSERT INTO City (`name`, `region`) VALUES("Waltham", "MA");
INSERT INTO City (`name`, `region`) VALUES("Warner Robins", "GA");
INSERT INTO City (`name`, `region`) VALUES("Warren", "MI");
INSERT INTO City (`name`, `region`) VALUES("Warrensburg", "MO");
INSERT INTO City (`name`, `region`) VALUES("Warrenton", "VA");
INSERT INTO City (`name`, `region`) VALUES("Warsaw", "IN");
INSERT INTO City (`name`, `region`) VALUES("Washington", "DC");
INSERT INTO City (`name`, `region`) VALUES("Wasilla", "AK");
INSERT INTO City (`name`, `region`) VALUES("Waterbury", "CT");
INSERT INTO City (`name`, `region`) VALUES("Waterloo", "IA");
INSERT INTO City (`name`, `region`) VALUES("Watertown", "NY");
INSERT INTO City (`name`, `region`) VALUES("Watertown", "SD");
INSERT INTO City (`name`, `region`) VALUES("Watsonville", "CA");
INSERT INTO City (`name`, `region`) VALUES("Waukegan", "IL");
INSERT INTO City (`name`, `region`) VALUES("Waukesha", "WI");
INSERT INTO City (`name`, `region`) VALUES("Wausau", "WI");
INSERT INTO City (`name`, `region`) VALUES("Waycross", "GA");
INSERT INTO City (`name`, `region`) VALUES("Wayne", "PA");
INSERT INTO City (`name`, `region`) VALUES("Waynesboro", "VA");
INSERT INTO City (`name`, `region`) VALUES("Waynesville", "MO");
INSERT INTO City (`name`, `region`) VALUES("Weatherford", "TX");
INSERT INTO City (`name`, `region`) VALUES("Webb City", "MO");
INSERT INTO City (`name`, `region`) VALUES("Webster", "NY");
INSERT INTO City (`name`, `region`) VALUES("Wenatchee", "WA");
INSERT INTO City (`name`, `region`) VALUES("Wentzville", "MO");
INSERT INTO City (`name`, `region`) VALUES("Weslaco", "TX");
INSERT INTO City (`name`, `region`) VALUES("West Bend", "WI");
INSERT INTO City (`name`, `region`) VALUES("West Caldwell", "NJ");
INSERT INTO City (`name`, `region`) VALUES("West Chester", "PA");
INSERT INTO City (`name`, `region`) VALUES("West Hartford", "CT");
INSERT INTO City (`name`, `region`) VALUES("West Hollywood", "CA");
INSERT INTO City (`name`, `region`) VALUES("West Lafayette", "IN");
INSERT INTO City (`name`, `region`) VALUES("West New York", "NJ");
INSERT INTO City (`name`, `region`) VALUES("West Orange", "NJ");
INSERT INTO City (`name`, `region`) VALUES("West Palm Beach", "FL");
INSERT INTO City (`name`, `region`) VALUES("West Plains", "MO");
INSERT INTO City (`name`, `region`) VALUES("West Richland", "WA");
INSERT INTO City (`name`, `region`) VALUES("West Warwick", "RI");
INSERT INTO City (`name`, `region`) VALUES("Westborough", "MA");
INSERT INTO City (`name`, `region`) VALUES("Westerville", "OH");
INSERT INTO City (`name`, `region`) VALUES("Westfield", "MA");
INSERT INTO City (`name`, `region`) VALUES("Westhampton Beach", "NY");
INSERT INTO City (`name`, `region`) VALUES("Westminster", "CA");
INSERT INTO City (`name`, `region`) VALUES("Westminster", "MD");
INSERT INTO City (`name`, `region`) VALUES("Weston", "FL");
INSERT INTO City (`name`, `region`) VALUES("Westport", "CT");
INSERT INTO City (`name`, `region`) VALUES("Wheaton", "IL");
INSERT INTO City (`name`, `region`) VALUES("Wheeling", "WV");
INSERT INTO City (`name`, `region`) VALUES("Whidbey Island", "WA");
INSERT INTO City (`name`, `region`) VALUES("White Plains", "NY");
INSERT INTO City (`name`, `region`) VALUES("Wichita Falls", "TX");
INSERT INTO City (`name`, `region`) VALUES("Wichita", "KS");
INSERT INTO City (`name`, `region`) VALUES("Wilkes-Barre", "PA");
INSERT INTO City (`name`, `region`) VALUES("Williamsburg", "VA");
INSERT INTO City (`name`, `region`) VALUES("Williamsport", "PA");
INSERT INTO City (`name`, `region`) VALUES("Willimantic", "CT");
INSERT INTO City (`name`, `region`) VALUES("Williston", "ND");
INSERT INTO City (`name`, `region`) VALUES("Willoughby", "OH");
INSERT INTO City (`name`, `region`) VALUES("Wilmington", "DE");
INSERT INTO City (`name`, `region`) VALUES("Wilmington", "NC");
INSERT INTO City (`name`, `region`) VALUES("Wilmington", "OH");
INSERT INTO City (`name`, `region`) VALUES("Winchester", "VA");
INSERT INTO City (`name`, `region`) VALUES("Winder", "GA");
INSERT INTO City (`name`, `region`) VALUES("Windsor", "CT");
INSERT INTO City (`name`, `region`) VALUES("Winfield", "AL");
INSERT INTO City (`name`, `region`) VALUES("Winnemucca", "NV");
INSERT INTO City (`name`, `region`) VALUES("Winona", "MN");
INSERT INTO City (`name`, `region`) VALUES("Winston-Salem", "NC");
INSERT INTO City (`name`, `region`) VALUES("Winter Haven", "FL");
INSERT INTO City (`name`, `region`) VALUES("Wisconsin Rapids", "WI");
INSERT INTO City (`name`, `region`) VALUES("Wixom", "MI");
INSERT INTO City (`name`, `region`) VALUES("Woodbridge", "NJ");
INSERT INTO City (`name`, `region`) VALUES("Woodbridge", "VA");
INSERT INTO City (`name`, `region`) VALUES("Woodbury", "NY");
INSERT INTO City (`name`, `region`) VALUES("Woodinville", "WA");
INSERT INTO City (`name`, `region`) VALUES("Woodstock", "GA");
INSERT INTO City (`name`, `region`) VALUES("Woodstock", "IL");
INSERT INTO City (`name`, `region`) VALUES("Woodstock", "NY");
INSERT INTO City (`name`, `region`) VALUES("Woonsocket", "RI");
INSERT INTO City (`name`, `region`) VALUES("Wooster", "OH");
INSERT INTO City (`name`, `region`) VALUES("Worcester", "MA");
INSERT INTO City (`name`, `region`) VALUES("Wyandotte", "MI");
INSERT INTO City (`name`, `region`) VALUES("Wylie", "TX");
INSERT INTO City (`name`, `region`) VALUES("Yakima", "WA");
INSERT INTO City (`name`, `region`) VALUES("Yankton", "SD");
INSERT INTO City (`name`, `region`) VALUES("Yardley", "PA");
INSERT INTO City (`name`, `region`) VALUES("Yelm", "WA");
INSERT INTO City (`name`, `region`) VALUES("Yonkers", "NY");
INSERT INTO City (`name`, `region`) VALUES("Yorba Linda", "CA");
INSERT INTO City (`name`, `region`) VALUES("York", "ME");
INSERT INTO City (`name`, `region`) VALUES("York", "PA");
INSERT INTO City (`name`, `region`) VALUES("Yorktown", "VA");
INSERT INTO City (`name`, `region`) VALUES("Yorkville", "IL");
INSERT INTO City (`name`, `region`) VALUES("Youngstown", "OH");
INSERT INTO City (`name`, `region`) VALUES("Ypsilanti", "MI");
INSERT INTO City (`name`, `region`) VALUES("Yreka", "CA");
INSERT INTO City (`name`, `region`) VALUES("Yuba City", "CA");
INSERT INTO City (`name`, `region`) VALUES("Yucaipa", "CA");
INSERT INTO City (`name`, `region`) VALUES("Yucca Valley", "CA");
INSERT INTO City (`name`, `region`) VALUES("Yukon", "OK");
INSERT INTO City (`name`, `region`) VALUES("Yuma", "AZ");
INSERT INTO City (`name`, `region`) VALUES("Zanesville", "OH");
INSERT INTO City (`name`, `region`) VALUES("Zephyrhills", "FL");
INSERT INTO City (`name`, `region`) VALUES("Zion", "IL");